### ISSUE TITLE
Spatial Navigation - change key bindings

### ISSUE THREAD

**Issue by mgraham** [The-Compiler/qutebrowser#579] opened 2015-03-26 14:59 UTC
When spatial navigation is turned on, the arrow keys are used to navigate links, instead of scrolling.  Is there any way to rebind different keys to spatial navigation (e.g. ctrl-up, etc.)?

**Comment by The-Compiler** [comment] 2015-03-30 07:56
Whoops - missed that one! Similiar to #578, this won't be possible without completely reimplementing spatial navigation (which comes with its own set of problems I could imagine...).

I suggest using hints instead :)

**Comment by mgraham** [comment] 2015-04-07 17:55
What I've done is treat spatial navigation like a new mode.  I put this in keys.conf:

```
set input spatial-navigation true
    <f12>

set input spatial-navigation false
    <f11>
```

That way I can use the arrows to navigate links after I toggle it on.

It would be nice if there were a way of putting a colour indicator in the status bar to indicate the mode change.

Also, it would be nice to be able to toggle a boolean value, like so:


```
set input spatial-navigation toggle
    <f12>
```

**Comment by The-Compiler** [comment] 2015-04-07 18:01
Hmm, interesting. I might think about adding spatial navigation as a "real" mode.

I'd like some generic way to add indicators for certain options to the statusbar, but I can't think of a good way to configure that - so probably that'll wait until plugin support is there (#30).

You can already toggle the value using `:set input spatial-navigation!` (like in vim - see `:help :set`). :smile:

**Comment by mgraham** [comment] 2015-04-07 20:54
Oh great!  Thanks for the toggle syntax!

I'd vote for a separate mode.  One advantage of a separate mode over my toggle approach is that you could have it enabled or disabled by default on page load.  Often I want to use spatial navigation for pages where links are too cluttered to use the hints.  When I end up on the new page, I'd want to be back in normal mode again.

Should I enter a feature request? :)

**Comment by The-Compiler** [comment] 2015-04-07 20:59
Gotta thank @smalltock for that one :wink:

Yeah, please open a new issue and mention this one in it :)

**Comment by mgraham** [comment] 2015-04-14 17:41
It seems to me that one way of hacking up this feature would be to:

* turn on spatial navigation
* send the cursor key
* turn off spatial navigation

Something like:
```
set input spatial-navigation true;;send <up>;;set input spatial navigation false
    <shift-up>
```

Is this sort of what you were suggesting in #626?

**Comment by The-Compiler** [comment] 2015-04-14 20:12
I haven't had time to look at #626 in detail yet - I think it's essentially proposing a new mode for the caret mode, and using QWebPage actions to bind <kbd>hjkl</kbd>.

Would a separate mode for spatial navigation work for you? I don't really like the idea of toggling it on/off with each keypress...

Also see #556 for a command to send a keypress.

**Comment by mgraham** [comment] 2015-04-14 21:28
Personally, I'd prefer keybindings, because that's what I'm used to from Opera.  But I'm sure I can eventually get used to a spatial navigation mode as well. :)

**Comment by The-Compiler** [comment] 2015-04-22 04:49
After looking at #626 it seems selecting other elements in spatial navigation mode is actually possible using WebActions, which means it'd be possible to add custom keybindings! :smile:

**Comment by The-Compiler** [comment] 2015-05-22 05:09
I recently (f49dba6e38a5ed4fbd6a2d8e9920310c2c22ed74) changed scrolling via <kbd>hjkl</kbd> so it uses fake keypresses because scrolling via the API was unreliable sometimes.

I just noticed that this means using <kbd>hjkl</kbd> with spatial navigation enabled will actually navigate via spatial navigation rather than scroll.

@mgraham - what's your opinion on this? I can think of these options:

* Leave it as-is, as going up/down via spatial navigation is often similiar to scrolling.
* Change <kbd>hjkl</kbd> to scroll anyways, and add commands (which *can* be custom-bound) for spatial navigation.
* Like 2), but add a separate mode for spatial navigation too.

**Comment by mgraham** [comment] 2015-05-22 17:58
I would vote for option 3, even thought it is obviously more work :)   

Personally, I would use custom-bound keys for spatial navigation myself, but I think that because qutebrowser is a modal browser, it's probably more consistent spatial navigation mode.

**Comment by The-Compiler** [comment] 2015-10-01 09:38
This is actually a duplicate of #609 now :wink:

**Closed by The-Compiler** 2015-10-01 09:38 UTC
