### ISSUE TITLE
Crashes on geektyper.com

### ISSUE THREAD

**Issue by ravench** [The-Compiler/qutebrowser#764] opened 2015-06-17 18:15 UTC
Crashes when clicking the first entry ("Geek Typer (saving)") on http://geektyper.com

```
Fatal Python error: Segmentation fault

Current thread 0x00007f9414730700 (most recent call first):
  File "/home/simon/src/qutebrowser/qutebrowser/app.py", line 127 in qt_mainloop
  File "/home/simon/src/qutebrowser/qutebrowser/app.py", line 117 in run
  File "/home/simon/src/qutebrowser/qutebrowser/qutebrowser.py", line 149 in main
  File "/home/simon/src/qutebrowser/qutebrowser/__main__.py", line 29 in <module>
  File "/usr/lib/python3.4/runpy.py", line 85 in _run_code
  File "/usr/lib/python3.4/runpy.py", line 170 in _run_module_as_main
/home/simon/bin/qutebrowser: line 2: 20450 Segmentation fault      ~/src/qutebrowser/.venv/bin/python3 -m qutebrowser "$@"
```

This is on a fresh Debian-experimental install with adblock turned on.

**Comment by The-Compiler** [comment] 2015-06-17 18:40
Can you reproduce this reliably? I can't reproduce it here, so I'm going to guess this is something fixed in non-ancient Qt versions (i.e. on distributions other than Debian/Ubuntu).

**Closed by The-Compiler** 2015-06-17 18:40 UTC

**Comment by The-Compiler** [comment] 2015-06-18 07:04
FWIW, I can't reproduce this on Debian Jessie (with Qt 5.3.2) either. What Qt version are you running?

**Comment by ravench** [comment] 2015-06-18 17:15
After rebooting and pulling I can't reproduce it anymore, either..
But it was quite reliable before.

**Comment by The-Compiler** [comment] 2015-06-18 17:26
Oh well... Let's pretend it didn't happen then :wink:. Thanks for the report though!
