### ISSUE TITLE
confirm-quit

### ISSUE THREAD

**Issue by thebaum** [The-Compiler/qutebrowser#1086] opened 2015-11-04 00:36 UTC
Confirm-quit doesn't apply if the browser is closed by typing ":q"

**Comment by The-Compiler** [comment] 2015-11-04 05:20
I can't reproduce this. I set `confirm-quit` to `multiple-tabs`, and I get a confirmation when I do `:q`. How did you test this precisely? Maybe you're running into #846?

**Comment by thebaum** [comment] 2015-11-04 11:38
I just figured out that the whole browser crashs once i enter `:q` , thus `confirm-quit` should be fine

**Comment by The-Compiler** [comment] 2015-11-04 11:44
You mean "quits", not "crashes" :wink: Closing this as that's how `:quit` is intended to work.

**Closed** 2015-11-04 12:09 UTC
Labels: can't reproduce
