### ISSUE TITLE
[[bug]] – <ctrl-tab> Doesn't Seem to Be Recognized by Qutebrowser on Mac OS

### ISSUE THREAD

**Issue by WammKD** [The-Compiler/qutebrowser#2142] opened 2016-11-26 02:42 UTC
First, I love that I can use the same browser on all of my operating systems.

I've found that <ctrl-tab> doesn't seem to be recognized for any assigned command on my MacBook Air. I've tried a few and it never seems to do anything. All other commands seem to work just fine, though. The OS version is Mac OSX 10.11.5 and the Qutebrowser version is the latest version on brew, v0.8.2 (I know that's 0.0.2 behind the most recent version so perhaps that's the issue? I didn't see it mentioned anywhere in the issues so I thought I'd bring it up, just in case).

**Comment by The-Compiler** [comment] 2016-11-26 07:03
Do other commands with Ctrl work fine? Is this with the MacBook's built-in keyboard?

Can you please also reproduce this (ideally after starting in a terminal with `--temp-basedir`) and then do `:report` so I get a debug log?

Pinging @tjanson and @victorpopkov for the cask update (as you are the ones doing previous updates). FWIW, there's also a [qutebrowser-announce](https://lists.schokokeks.org/mailman/listinfo.cgi/qutebrowser-announce) mailinglist in case you're interested and didn't know yet :wink:

**Comment by WammKD** [comment] 2016-11-28 04:21
Yeah; as far as I can tell. I usually use Linux and, then, Windows so I hate the keybindings on the Mac so I was overjoyed to realize I could bind however I wished on the Mac with Qutebrowser and I usually use standard web browser keybindings so plenty of Control keys to check with (`<ctrl-w>`, `<ctrl-t>`, `<ctrl-d>`, `<ctrl-p>`; even `<ctrl-pageup>` and `<ctrl-pagedown>` for switching tabs and `<ctrl-shift-pageup/-down>` for moving tabs work just fine). For some reason, `<ctrl-tab>` isn't working, though.

Yep; using the built-in keyboard.

Sure thing; it's been done and sent. I hope that helps narrow things down.

I did _not_ know and am definitely interested in. This browser is really cool and feels really put together and thought-through.

**Comment by The-Compiler** [comment] 2016-11-28 05:37
So as you mentioned, `ctrl-t` seems to work fine:

```
22:01:03 DEBUG    modes      modeman:_eventFilter_keypress:169 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
22:01:03 DEBUG    commands   command:run:508 command called: open ['-t']
[...]
22:01:03 DEBUG    modes      modeman:_eventFilter_keypress:194 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True --> filter: True (focused: <qutebrowser.browser.webkit.webview.WebView tab_id=1 url=''>)
```

While for `ctrl-tab`, we only get `0x1000022`, which is `Qt::Key_Meta` with the comment "On OS X, this corresponds to the Control keys. ":

```
22:01:30 DEBUG    modes      modeman:_eventFilter_keypress:169 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
22:01:30 DEBUG    keyboard   basekeyparser:_debug_log:111 Ignoring only-modifier keyeevent.
22:01:30 DEBUG    keyboard   basekeyparser:_debug_log:111 Got key: 0x1000022 / text: ''
22:01:30 DEBUG    keyboard   basekeyparser:_debug_log:111 Ignoring, no text char
22:01:30 DEBUG    modes      modeman:_eventFilter_keypress:194 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True --> filter: False (focused: <qutebrowser.browser.webkit.webview.WebView tab_id=1 url='https://duckduckgo.com/'>)
```

Some ideas/questions:

- Does your tab key work at all? :wink:
- Can you somehow test `ctrl-tab` in another application?
- OS X might somehow handle `ctrl-tab` itself?
- Or maybe it's a [ghosting](https://www.microsoft.com/appliedsciences/antighostingexplained.mspx) issue and `ctrl-tab` won't work at all? (though I'd find that a bit strange with ctrl)

**Comment by HolySmoke86** [comment] 2016-11-28 12:01
`Ctrl-Tab` seems to be specially handled by OSX/Coca text input method. Chromium devs mentioned having had to fight with it here: https://www.chromium.org/developers/os-x-keyboard-handling
The missing keypress event of `Tab` right after `Ctrl` also suggest an intercept from a level higher up.

I don't suppose it's ghosting, since the modifier keys usually aren't part of the grid and have their own lines due to high probability of many of them being pressed together.

**Comment by The-Compiler** [comment] 2016-11-29 06:14
This already seems to be tracked in [QTBUG-8596](https://bugreports.qt.io/browse/QTBUG-8596) (with the linked comment having some more information), so I'm closing this.

**Closed by The-Compiler** 2016-11-29 06:14 UTC
Labels: os: OS X, priority: 2 - low
