### ISSUE TITLE
:bookmark-load background highlighting quirk

### ISSUE THREAD

**Issue by sdothum** [The-Compiler/qutebrowser#1519] opened 2016-05-22 21:20 UTC
:bookmark-load tab highlighting requires 2 tab presses to highlight list entry. Background highlight appears to clear after first tab. Second tab highlights entry. 

Regardless, after the first tab, hitting return completes the selection.

**Comment by The-Compiler** [comment] 2016-05-23 06:23
Can you elaborate? I get this when I press `space`, `tab` after `:bookmark-load` is selected:

![test](https://cloud.githubusercontent.com/assets/625793/15461982/a793ae58-20bf-11e6-8117-dfbd2d6e2f6b.gif)

**Comment by sdothum** [comment] 2016-05-23 13:37
Ah. the use case is: if the search yields only one selection, on the first tab (for say a 'gb' action), the complete url is highligted 'red' instead of a 'yellow' bg. On the second tab, the bg is turned 'yellow'. 

Maybe this is the intended behaviour. I found it confusing (until I got used to it :-)

**Comment by The-Compiler** [comment] 2016-05-23 17:56
I still don't understand, sorry - can you show a screenshot or ideally a gif like above (recorded via `sleep 1 && byzanz-record -h 100 -w 300 -y 668 test.gif`, adjust `-y` for your screen dimensions)?

**Comment by NoctuaNivalis** [comment] 2016-05-24 07:49
I can reproduce this:
* Type  `:quickmark-load`
* Type some words until you have a unique match
* Hit tab

The unique match will flash yellow, will then be displayed in a red font (as in, this whole quickmark matches the query). A second tab will select it in yellow.

**Comment by The-Compiler** [comment] 2016-05-24 19:10
Still no luck on my side:

![test](https://cloud.githubusercontent.com/assets/625793/15516620/e93eeb6c-21f3-11e6-9add-89bcf45dfccb.gif)

This is with one tab-press.

Can you try to reproduce it when doing `--temp-basedir` and adding a few quickmarks by hand?

**Comment by lahwaacz** [comment] 2016-05-24 20:05
I can reproduce the steps by @NoctuaNivalis even with `--temp-basedir`.

**Comment by The-Compiler** [comment] 2016-05-24 20:09
That's odd - can someone of you please do `:report` after reproducing the issue?

**Comment by NoctuaNivalis** [comment] 2016-05-24 20:16
Just a sec.

**Comment by NoctuaNivalis** [comment] 2016-05-24 20:19
Here's a desktop record of the issue, though you can't see the "flash" due to bad video quality.

[out.ogv.zip](https://github.com/The-Compiler/qutebrowser/files/280435/out.ogv.zip)

**Comment by The-Compiler** [comment] 2016-05-24 20:38
log without the issue:

```
22:34:56 DEBUG    completion completer:update_completion:346 New completion for ['quickmark-load', 'qtbu']: QuickmarkCompletionModel, with pattern 'qtbu'
22:34:56 DEBUG    modes      modeman:_eventFilter_keyrelease:214 filter: False
22:34:58 DEBUG    modes      modeman:_eventFilter_keypress:169 got keypress in mode KeyMode.command - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='command' warn=True>
22:34:58 DEBUG    commands   command:run:488 command called: completion-item-next
22:34:58 DEBUG    commands   command:run:503 Calling qutebrowser.completion.completer.Completer.completion_item_next(<qutebrowser.completion.completer.Completer>)
22:34:58 DEBUG    completion completer:selection_changed:278 Will ignore next completion update.
22:34:58 DEBUG    completion completer:change_completed_part:441 changing part 1 to 'qtbug'
22:34:58 DEBUG    completion completer:schedule_completion_update:294 Scheduling completion update.
22:34:58 DEBUG    completion completer:schedule_completion_update:291 Ignoring update because there were no changes.
22:34:58 DEBUG    completion completer:change_completed_part:459 Placing cursor after ':quickmark-load qtbug'
22:34:58 DEBUG    modes      completer:change_completed_part:460 Completion triggered, focusing <qutebrowser.completion.completer.Completer>
22:34:58 DEBUG    modes      modeman:_eventFilter_keypress:194 handled: True, forward-unbound-keys: auto, passthrough: True, is_non_alnum: True --> filter: True (focused: <qutebrowser.mainwindow.statusbar.command.Command>)
22:34:58 DEBUG    completion completer:update_cursor_part:427 cursor_part 1, spaces False
22:34:58 DEBUG    completion completer:update_completion:307 Updating completion - prefix :, parts ['quickmark-load', 'qtbug'], cursor_part 1
22:34:58 DEBUG    completion completer:update_completion:310 Ignoring completion update because ignore_change is True.
```

log with the issue:

```
22:16:22 DEBUG    completion completer:update_completion:346 New completion for ['quickmark-load', 'ba']: QuickmarkCompletionModel, with pattern 'ba'
22:16:22 DEBUG    modes      modeman:_eventFilter_keyrelease:214 filter: False
22:16:24 DEBUG    modes      modeman:_eventFilter_keypress:169 got keypress in mode KeyMode.command - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='command' warn=True>
22:16:24 DEBUG    commands   command:run:488 command called: completion-item-next
22:16:24 DEBUG    commands   command:run:503 Calling qutebrowser.completion.completer.Completer.completion_item_next(<qutebrowser.completion.completer.Completer>)
22:16:24 DEBUG    completion completer:change_completed_part:441 changing part 1 to 'bar'
22:16:24 DEBUG    completion completer:schedule_completion_update:294 Scheduling completion update.
22:16:24 DEBUG    completion completer:schedule_completion_update:291 Ignoring update because there were no changes.
22:16:24 DEBUG    completion completer:change_completed_part:459 Placing cursor after ':quickmark-load bar '
22:16:24 DEBUG    modes      completer:change_completed_part:460 Completion triggered, focusing <qutebrowser.completion.completer.Completer>
22:16:24 DEBUG    modes      modeman:_eventFilter_keypress:194 handled: True, forward-unbound-keys: auto, passthrough: True, is_non_alnum: True --> filter: True (focused: <qutebrowser.mainwindow.statusbar.command.Command>)
22:16:24 DEBUG    completion completer:update_cursor_part:427 cursor_part 1, spaces False
22:16:24 DEBUG    completion completer:update_completion:307 Updating completion - prefix :, parts ['quickmark-load', 'bar'], cursor_part 1
22:16:24 DEBUG    completion completer:_get_new_completion:203 Before filtering flags: parts ['quickmark-load', 'bar'], cursor_part 1
22:16:24 DEBUG    completion completer:_get_new_completion:206 After filtering flags: parts ['quickmark-load', 'bar'], cursor_part 1
22:16:24 DEBUG    completion completer:_get_new_completion:231 completions: *quickmark_by_name*
22:16:24 DEBUG    completion debug:__exit__:256 Setting filter pattern took 0.000554 seconds.
22:16:24 DEBUG    completion completer:update_completion:346 New completion for ['quickmark-load', 'bar']: QuickmarkCompletionModel, with pattern 'bar'
```

Looks like `completion completer:selection_changed:278 Will ignore next completion update.` is not logged int he second case?

**Comment by NoctuaNivalis** [comment] 2016-05-24 20:52
Well, d'you have quick-complete on? It's on for me, and I'd think the model has only one count (match), so the `Will ignore next completion update` shouldn't be logged.

```python
273         if model.count() == 1 and config.get('completion', 'quick-complete'):                                                                                                                                   
274             # If we only have one item, we want to apply it immediately                                                                                                                                         
275             # and go on to the next part.                                                                                                                                                                       
276             self.change_completed_part(data, immediate=True)
277         else:                                                                                                                                                                                                   
278             log.completion.debug("Will ignore next completion update.")                                                                                                                                         
279             self._ignore_change = True                                                                                                                                                                          
280             self.change_completed_part(data)
```

**Comment by The-Compiler** [comment] 2016-05-24 20:57
Doh! Reproduced now :laughing:. I thought `quick-complete` was false by default, and didn't test with `--temp-basedir` again.

**Comment by The-Compiler** [comment] 2016-08-29 05:18
This was fixed as part of #1811.

**Comment by rcorre** [comment] 2016-09-01 02:38
I don't think this is fixed. Start up with `--temp-basedir`, ensure `quick-complete` is `true`, and press `o``<TAB>``<TAB>`. The completion will flicker and not highlight the first time, then complete the second time. I think it is getting closed by `quick-complete`, but for some reason `set_model` is called after that with a non-`None` model which causes the completionwidget to activate again.

**Comment by The-Compiler** [comment] 2016-09-01 04:57
Ah, true. @mlochbaum or @rcorre, want to take a closer look? :wink:

**Comment by rcorre** [comment] 2016-09-01 10:56
After the first `TAB`, the text looks like `:open https://duckduckgo.com/ |` and 

```
(parts,self._cursor_part) = (['open', 'https://duckduckgo.com/'], 1)
```

`cursor_part` should be 2 here, I think.

**Comment by rcorre** [comment] 2016-09-01 17:36
I think I can fix this and clean up the `cursor_pos`/`parts` management at the same time.

**Closed** 2016-09-15 14:46 UTC
Labels: bug, component: completion, priority: 2 - low
