### ISSUE TITLE
Various prompts don't clearly ask the user what is needed

### ISSUE THREAD

**Issue by Earnestly** [The-Compiler/qutebrowser#1065] opened 2015-10-25 21:43 UTC
For example when making edits on github comments, if cancel is selected qutebrowser will provide a question in the statusbar with a blue background.  This question ends abruptly and  the choice of options is not provided. 

Most CLI tooling will prompt with a simple `[Y/n]` where bias is denoted by the capitalised letter.  Even pressing Return which is common in such situations doesn't do anything.

Consider adding a note about the kind of response it is asking for.  I did eventually fumble around due to past experience that `y` and `n` are apparently required.

**Comment by The-Compiler** [comment] 2015-10-25 21:48
The message being cut off should be fixed with #368.

I can't reproduce the message on GitHub, but pressing enter should work, as it's bound to `:prompt-accept` in prompt mode by default.

I agree the keys should be shown - I thought there was already an issue for this, but it seems not.

**Comment by The-Compiler** [comment] 2016-05-04 15:13
Ah, there *is* one: #630

**Closed by The-Compiler** 2016-05-04 15:13 UTC
Labels: priority: 1 - middle
