### ISSUE TITLE
Maximizing window restarts YouTube videos

### ISSUE THREAD

**Issue by TheGag96** [The-Compiler/qutebrowser#2136] opened 2016-11-21 21:52 UTC
v0.8.4, Windows 64-bit

I was messing around with the window while playing a YouTube video and noticed doing so will restart the video entirely, though it doesn't appear to be refreshing the page (just reinitializing all elements?).

**Comment by The-Compiler** [comment] 2016-11-22 06:17
Using the release from the download page I presume? I can't reproduce this in my Windows 8 VM FWIW.

**Comment by TheGag96** [comment] 2016-11-22 20:45
Yes, just from the releases page. Only difference is that I'm running 8.1... Odd. I can very easily produce it just by playing a YouTube video and hitting maximize (though resizing the window at the borders does not cause it).

**Comment by quonic** [comment] 2016-11-22 20:48
v0.8.4, Windows 64-bit
OS: Windows 10 Build 14393

I can reproduce it with the latest release. It seems to happen when maximizing and unmaximizing.

**Comment by The-Compiler** [comment] 2016-11-22 21:30
Can you also reproduce this when running `qutebrowser --debug --temp-basedir` from a terminal? And do you see any interesting output when maximizing?

**Comment by TheGag96** [comment] 2016-11-30 05:32
I tried running it from a terminal but the prompt returns right after qutebrowser launches... (Sorry for being late to report back with this!)

**Comment by The-Compiler** [comment] 2016-11-30 06:45
Oh, right, qutebrowser has no terminal output on Windows... Can you reproduce it (ideally with `--temp-basedir` again) and then do `:report` so I get a debug log?

Also, no worries - it's not like I'd run out of other stuff to do :laughing:

**Comment by TheGag96** [comment] 2016-12-02 00:33
http://pastebin.com/63U8xGQq

Will this help?

**Comment by The-Compiler** [comment] 2016-12-02 05:30
Yep, unfortunately there's nothing interesting in there though...

Can you please try to reproduce this with https://sourceforge.net/projects/otter-browser/files/otter-browser-weekly135/ (with that older weekly 135, not a newer one)?

What I'd guess is that this is some kind of QtWebKit issue, and probably solved in the future with QtWebEngine (the new backend).

**Comment by TheGag96** [comment] 2016-12-03 21:23
Just grabbed the win64 weekly 135 (they were all modified today it seems) and it does  not happen there, although like qutebrowser does occasionally, maximizing does mess up the video rendering a bit (most of the video becomes black).

**Comment by The-Compiler** [comment] 2016-12-05 06:38
Hmm, interesting. Unfortunately qutebrowser's Windows build doesn't work with QtWebEngine yet - but if it works there, I'll probably just close this as there isn't really much I can do.

**Comment by karic** [comment] 2016-12-23 18:37
Using ubuntu 16.04 and i3wm, when adding another tile it restarts the video, though tried it once again now and it doesn't restart it. Here is the pastebin when I was able to replicate the problem.
http://pastebin.com/ujQhjE4f

**Comment by The-Compiler** [comment] 2017-01-24 21:40
Since this is probably some weird QtWebKit issue I have no control over (and will most likely be gone once qutebrowser does QtWebEngine on Windows), I'm closing this.

**Closed by The-Compiler** 2017-01-24 21:40 UTC
Labels: can't reproduce, os: windows
