### ISSUE TITLE
With default zoom set to something that's not 100%, large images don't fit in the window.

### ISSUE THREAD

**Issue by daniel-lawrence-lu** [The-Compiler/qutebrowser#963] opened 2015-09-24 00:08 UTC
Usually, when viewing a large image that does not fit in the window (e.g. https://upload.wikimedia.org/wikipedia/commons/2/21/Carnegie_Mellon_University_as_seen_from_the_Cathedral_of_Learning.jpg ) we can toggle between two modes by clicking on the image:

1) the "zoomed out" mode that scales the image so that it fits in the screen
2) the "zoomed in" mode that removes scaling so that the image matches the screen's physical pixels 1:1

But when default-zoom setting is set to something that's not 100%, (e.g. 130%)

1) the "zoomed out" mode still requires scrolling to see the whole picture
2) the "zoomed in" mode is still scaled by the zoom level so that the picture is not sharp

**Comment by The-Compiler** [comment] 2015-09-25 05:40
I can confirm this - it seems the QtWebKit image view is affected by the zoom, while it probably shouldn't be.

**Comment by The-Compiler** [comment] 2017-01-24 22:12
This seems to be the behavior with QtWebEngine and in other browsers as well, so I'm closing this.

**Closed by The-Compiler** 2017-01-24 22:12 UTC
Labels: priority: 2 - low
