### ISSUE TITLE
Answering desktop notifications prompt at all results in 100% CPU/Extreme RAM Usage until Crash

### ISSUE THREAD

**Issue by zerojay** [The-Compiler/qutebrowser#1072] opened 2015-10-27 10:07 UTC
When going to any website that prompts you about whether or not you wish to allow the site to give you desktop notifications (facebook, for example), responding either yes or no to the prompt results in qutebrowser taking up 100% CPU utilization and causes RAM use to explode. The process very very quickly freezes and must be killed off with kill -9 to get things back to normal again. Sometimes it will end up crashing, other times it remains frozen entirely until the user manually kills it off.

This is happening on an up-to-date 32-bit install of Arch Linux and also happened on a 64-bit Ubuntu 15.04 installation.

**Comment by The-Compiler** [comment] 2015-10-27 10:10
Can you reproduce this on [this page](http://www.bennish.net/web-notifications.html)? Some people report trouble with notifications, but I haven't had any issues myself...

Can you start with `qutebrowser --temp-basedir --debug http://www.bennish.net/web-notifications.html`, reproduce it there, and show the output?

**Comment by The-Compiler** [comment] 2015-11-04 05:34
Any update on this, @zerojay?

**Comment by The-Compiler** [comment] 2016-01-07 09:38
Closing this as I can't reproduce it and @zerojay doesn't answer :wink:

**Closed by The-Compiler** 2016-01-07 09:38 UTC
Labels: can't reproduce
