### ISSUE TITLE
[Feature Request] Save state information for the event of a crash

### ISSUE THREAD

**Issue by smalltock** [The-Compiler/qutebrowser#1679] opened 2016-07-24 01:22 UTC
It bugs me like hell when I've got 10 important tabs open and suddenly webkit crashes and I lose everything. I think it'd be useful to periodically save a list of open tabs and their URLs to /tmp/ so that when QB is restarted after a crash, it'll open re-open those tabs.

**Comment by Kingdread** [comment] 2016-07-24 08:49
Duplicate of #11.

The problem is that the crash might be caused by a page, and restoring that page would just cause another crash, and so on, so you'd need some kind of better interface to select the pages.

**Closed by Kingdread** 2016-07-24 08:49 UTC
