### ISSUE TITLE
Misplaced hints for multi-line links

### ISSUE THREAD

**Issue by sudo-nice** [The-Compiler/qutebrowser#1182] opened 2015-12-11 08:17 UTC
1. Go to https://www.ruby-lang.org/en/news/2015/12/11/ruby-2-3-0-preview2-released/
2. Run `hint all tab`
3. See this (some plain text is hinted and some actual url is not):
![screenshot](http://i.imgur.com/qeyefmE.png)

Can you reproduce it, do you need more info?

**Comment by The-Compiler** [comment] 2015-12-11 08:43
I've been aware of the problem since months, but it seems there wasn't an issue opened for it yet. The problem is that QtWebKit only gives us the bounding rectangle of a link, which makes it impossible to tell where to place the hint when a link spans multiple lines.

**Comment by lamarpavel** [comment] 2016-02-01 22:06
I think I have a solution: Instead of emulating a click in the middle of the bounding box, click at the top right (roughly).
For normal links this should not change anything as in that case the entire bounding box is filled with the link. For links spanning multiple lines, the link must reach the end of the first line (or it wouldn't be broken into the next line). This guarantee should stand for links broken over any number of lines.

Now, instead of chosing the uppermost, rightmost pixel of the bounding box, add a small offset (possibly based on the configured font size) for good measure.

I don't have much time now to test this, otherwise I would have sent a PR, but maybe someone else can find the time.

**Comment by The-Compiler** [comment] 2016-02-01 22:10
I think I tried different click positions some months ago and all of them had some drawbacks and some advantages.

I'm again going to mention I really want to write some tests for the corner cases still in my head before touching any hint logic, but I've not gotten to it yet :laughing:

**Comment by lahwaacz** [comment] 2016-02-05 14:05
I think there might be another trick using JavaScript's `Element.getClientRects()` method: :wink:
http://help.dottoro.com/ljxsdaqk.php
https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects#Specifications

**Comment by lahwaacz** [comment] 2016-05-20 20:11
The position of the hint label should be addressed by the second commit in #1433. Note that the click position is already correct for this case since #1311.

**Closed** 2016-06-06 19:21 UTC
Labels: bug, component: hints, priority: 1 - middle
