### ISSUE TITLE
Nextcloud calender never fully loads

### ISSUE THREAD

**Issue by mrgrumpyarse** [The-Compiler/qutebrowser#2040] opened 2016-10-20 12:05 UTC
Name            : qutebrowser-git
Version         : r10434.ebe656f-1

Nextcloud calender never completely loads, the back ground page ie a blank calender loads quickly but never populates with the actual calender entries.

![nextcloud_calender_firefox](https://cloud.githubusercontent.com/assets/22820949/19558924/e9fd0f16-96c4-11e6-9869-d7ff3b14a45a.png)

![nextcloud_calender_qutebrowser](https://cloud.githubusercontent.com/assets/22820949/19558923/e9f8968e-96c4-11e6-8cb4-fd43e33550c0.png)

[qutebrowser_vdebug_message.txt](https://github.com/The-Compiler/qutebrowser/files/541610/qutebrowser_vdebug_message.txt)

apologies in advance if this is my incompetence

**Comment by The-Compiler** [comment] 2016-10-21 05:39
Can I reproduce this on https://demo.nextcloud.com/ somehow? I can't seem to find a calendar there, even in the install apps screen.

Also, what distribution are you on?

**Comment by mrgrumpyarse** [comment] 2016-10-21 12:15
I am on Arch linux,
Linux kernal 4.8.2-1-ARCH  x86_64 GNU/Linux,  

Both my machines display the same issue.  One running KDE Plasma 5.8.2 the other on the latest git build of sway ( re-write of i3 window manager for wayland - https://github.com/SirCmpwn/sway)

Ive put up a Digital Ocean droplet running Ubuntu 16.04 lts and set up Nextcloud for you to use.
Its purely for your testing, so do what you want with it - Its snapshotted so can easily be reset and  will be destroyed when your done with it.

I will send the details via the contact info on your blog page

**Comment by The-Compiler** [comment] 2016-10-21 12:42
Thank you! I can reproduce this with the QtWebKit backend, and unfortunately there is nothing I can do about that...

However, it seems to be fixed with the upcoming QtWebEngine backend, which can you try by installing `qt5-webengine` and launching qutebrowser with `--backend webengine` - however some things like downloads won't work there yet.

**Closed by The-Compiler** 2016-10-21 12:42 UTC
