### ISSUE TITLE
Way to display strings and icons such as FontAwesome in UI

### ISSUE THREAD

**Issue by RomanSC** [The-Compiler/qutebrowser#1555] opened 2016-06-06 22:12 UTC
This could be useful to display:

lock https://www.duckduckgo.com

unlocked http://www.duckduckgo.com

Whereas "lock" and "unlock" would represent the respective Font Awesome icons and should be possible to implement in a way that strings could also be used, especially since Font Awesome is just a font.

It would also be useful for displaying which tabs sound is currently playing for.

**Comment by The-Compiler** [comment] 2016-06-07 05:51
Closing this as a duplicate of #30 and #1052.

> It would also be useful for displaying which tabs sound is currently playing for.

I'm guessing that should better be shown in the *tab* bar?

FWIW QtWebEngine has [an API](http://doc-snapshots.qt.io/qt5-dev/qwebenginepage.html#recentlyAudible-prop) for that since 5.7, so I might just implement that at some point, but it's not a priority.

**Closed by The-Compiler** 2016-06-07 05:51 UTC
