### ISSUE TITLE
Can't insert <Esc> in a page

### ISSUE THREAD

**Issue by Carpetsmoker** [The-Compiler/qutebrowser#788] opened 2015-06-25 23:37 UTC
I am stuck in a page which tells me to "Press Escape to continue". I press `i` to enter insert mode, but I can send `<Esc>` to the page since that also leaves insert mode...

**Comment by B0073D** [comment] 2015-06-26 00:10
I am also having this issue.

**Comment by Permafacture** [comment] 2015-06-26 00:16
Duplicate of #551

**Closed** 2015-06-26 08:11 UTC
