### ISSUE TITLE
segfault(core dump) vaapi issues

### ISSUE THREAD

**Issue by pghpete** [The-Compiler/qutebrowser#1193] opened 2015-12-23 22:37 UTC
qutebrowser segfaults and core dumps while trying to view sites with gifs.
Version info...
qutebrowser v0.4.1
Git commit: v0.4.0-1168-ge9bf5fc (2015-12-21 11:19:01 +0100)

CPython: 3.5.1
Qt: 5.5.1, runtime: 5.5.1
PyQt: 5.5.1

--debug output

libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva error: /usr/lib/dri/i965_drv_video.so init failed
libva info: va_openDriver() returns -1
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva error: /usr/lib/dri/i965_drv_video.so init failed
libva info: va_openDriver() returns -1

(python:3507): GStreamer-CRITICAL **: 
Trying to dispose element play, but it is in READY instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.

(python:3507): GStreamer-CRITICAL **: gst_element_factory_get_static_pad_templates: assertion 'GST_IS_ELEMENT_FACTORY (factory)' failed

(python:3507): GStreamer-CRITICAL **: gst_element_factory_get_static_pad_templates: assertion 'GST_IS_ELEMENT_FACTORY (factory)' failed

(python:3507): GStreamer-CRITICAL **: gst_element_factory_get_static_pad_templates: assertion 'GST_IS_ELEMENT_FACTORY (factory)' failed

(python:3507): GStreamer-CRITICAL **: gst_element_factory_get_static_pad_templates: assertion 'GST_IS_ELEMENT_FACTORY (factory)' failed
Fatal Python error: Segmentation fault

Thread 0x00007f11e380b700 (most recent call first):
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 121 in qt_mainloop
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 111 in run
  File "/usr/lib/python3.5/site-packages/qutebrowser/qutebrowser.py", line 153 in main
  File "/usr/bin/qutlibva info: VA-API version 0.38.0
ebrowser", line 9 in <module>
libva info: va_getDriverName() returns 0
Segmentation fault (core dumped)

[pete@vostro ~]$ pacman -Q | grep libva
libva 1.6.1-1
libva-intel-driver 1.6.1-1
[pete@vostro ~]$ lspci | grep -i vga
00:02.0 VGA compatible controller: Intel Corporation Mobile GM965/GL960 Integrated Graphics Controller (primary) (rev 0c)

video driver.
xf86-video-intel 1:2.99.917+519+g8229390-0.1

Manjaro 
Linux vostro 4.3.3-2-MANJARO #1 SMP PREEMPT Fri Dec 18 10:26:02 UTC 2015 x86_64 GNU/Linux

The odd part about this is that it has been working up until a few days ago but I see no newly installed/upgraded packages that would be causing this. Any thoughts of where I might be able to look to solve this issue?

**Comment by The-Compiler** [comment] 2015-12-29 13:39
Sorry for the late answer - I was sick the past few days, but finally feeling better!

I don't think I can help you much though... Can you check if the same thing happens when you run some other Qt5/QtWebKit project, like [Otter Browser](http://otter-browser.org/)?

**Comment by pghpete** [comment] 2015-12-29 16:54
Sure, i'll try and get back to you, thanks.

On Tue, Dec 29, 2015 at 8:39 AM, Florian Bruhin <notifications@github.com>
wrote:

> Sorry for the late answer - I was sick the past few days, but finally
> feeling better!
>
> I don't think I can help you much though... Can you check if the same
> thing happens when you run some other Qt5/QtWebKit project, like Otter
> Browser <http://otter-browser.org/>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/The-Compiler/qutebrowser/issues/1193#issuecomment-167792262>
> .
>



-- 
Regards,
Pete

**Comment by pghpete** [comment] 2015-12-29 16:55
I too am just getting over something. Hope you feel better!

On Tue, Dec 29, 2015 at 11:54 AM, Pete <pjperfetti@gmail.com> wrote:

> Sure, i'll try and get back to you, thanks.
>
> On Tue, Dec 29, 2015 at 8:39 AM, Florian Bruhin <notifications@github.com>
> wrote:
>
>> Sorry for the late answer - I was sick the past few days, but finally
>> feeling better!
>>
>> I don't think I can help you much though... Can you check if the same
>> thing happens when you run some other Qt5/QtWebKit project, like Otter
>> Browser <http://otter-browser.org/>?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/The-Compiler/qutebrowser/issues/1193#issuecomment-167792262>
>> .
>>
>
>
>
> --
> Regards,
> Pete
>



-- 
Regards,
Pete

**Comment by pghpete** [comment] 2015-12-31 19:00
Just stumbled upon this, but using this url as an example...
http://i.imgur.com/Vb2Vyap.gifv

it doesn't load correctly and causes this problem only if 
set content allow-plugins is set to false

if I set it to yes it functions correctly. Is that odd that a simple gifv would do that and cause the browswer to have issues like this? Could be something strange in my setup. for now I guess this can be considered closed, or at least setting this to true can serve as a workaround

**Comment by lamarpavel** [comment] 2016-01-01 21:55
gifv is something entirely different from a gif, imgur are just out to confuse people it seems. A gifv is indeed not an image but a video, and most players would try to display it with video acceleration (hence the vaapi involvement). If you disallow certain media involving scripts, then those videos (gifvs) can not be displayed. It shouldn't segfault though.

**Comment by The-Compiler** [comment] 2016-01-04 05:31
@pghpete so you can't reproduce the segfault, correct? The image not loading with plugins disabled makes sense, see @lamarpavel's explanation.

I'll close this for now - I'm quite sure it's an upstream issue (in either Qt, GStreamer or your graphics driver) and I really can't do much without a reproducer.

**Closed by The-Compiler** 2016-01-04 05:31 UTC
