### ISSUE TITLE
Pressing Enter in Search Mode Should Open a Link

### ISSUE THREAD

**Issue by antoyo** [The-Compiler/qutebrowser#689] opened 2015-05-28 22:48 UTC
In dwb, if the user search text and the current search result is a link, pressing enter open this link (as if the user clicked on the link with the mouse).
Of course, if the current search result is not a link, it should do nothing.

**Comment by Carpetsmoker** [comment] 2015-05-29 11:37
Duplicate of https://github.com/The-Compiler/qutebrowser/issues/401

**Comment by The-Compiler** [comment] 2015-05-29 11:39
What @Carpetsmoker said :wink:

**Closed by The-Compiler** 2015-05-29 11:39 UTC
