### ISSUE TITLE
The browser explodes while scrolling in a specific webpage (see details)

### ISSUE THREAD

**Issue by pedromj** [The-Compiler/qutebrowser#568] opened 2015-03-19 10:43 UTC
The browser explodes while scrolling in the following webpage:

http://www.bicyclerollingresistance.com/road-bike-reviews

The problem may be in QtWebKit but "qutebrowser" should try to avoid the exploding, as other windows and tabs are also lost.

**Comment by The-Compiler** [comment] 2015-03-19 10:47
What do you mean with "explodes" exactly? Right now I can only test this on Debian with Qt 5.3.2 where the page works fine.

If this is a segfault, you should get a crash report window when restarting. Can you please report the crash there so I get some more info?

**Comment by pedromj** [comment] 2015-03-19 11:15
That it breaks and every window is closed. The fault log is below. The problem seems to appear when scrolling to the image that has some JS code, so maybe the user-agent string is important for this.

==== Fault log ====
Fatal Python error: Aborted

Current thread 0x00007f18bf839700 (most recent call first):
  File "/usr/lib/python3.4/site-packages/qutebrowser/browser/webview.py", line 490 in paintEvent
  File "/usr/lib/python3.4/site-packages/qutebrowser/qutebrowser.py", line 127 in qt_mainloop
  File "/usr/lib/python3.4/site-packages/qutebrowser/qutebrowser.py", line 136 in main
  File "/usr/bin/qutebrowser", line 9 in <module>


==== Version info ====
qutebrowser v0.1.3
Git commit: v0.1.1-502-gca22ed0 (2015-03-17 19:13:44 +0100)

CPython: 3.4.3
Qt: 5.4.1, runtime: 5.4.1
PyQt: 5.4.1
SIP: 4.16.6
colorlog: no
colorama: no
pypeg2: 2.15
jinja2: 2.7.3
pygments: 2.0.2
yaml: 3.11
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2 22 Jan 2015

Frozen: False
Platform: Linux-3.18.6-1-ARCH-x86_64-with-arch, 64bit
OS Version: arch

--- /etc/arch-release ---


--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"



==== Config ====
[general]
startpage = about:blank
[ui]
user-stylesheet = /home/pedro/.config/qutebrowser/my-stylesheet-dark.css
remove-finished-downloads = true
[network]
user-agent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36
[tabs]
background-tabs = true
select-on-remove = previous
last-close = close
hide-auto = true
[content]
host-block-lists = http://www.malwaredomainlist.com/hostslist/hosts.txt,http://someonewhocares.org/hosts/hosts,http://winhelp2002.mvps.org/hosts.zip,http://malwaredomains.lehigh.edu/files/justdomains.zip,http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext,http://hosts-file.net/ad_servers.asp
[hints]
border = 1px solid orange
opacity = 1.0
chars = fdsartgbvecwxqyiopmnhzulkj
uppercase = true
[searchengines]
2es = https://translate.google.com/#en/es/{}
g = ${google}
2en = https://translate.google.com/#es/en/{}
wikipedia = http://en.wikipedia.org/w/index.php?title=Special:Search&search={}
wres = http://www.wordreference.com/redirect/translation.aspx?w={}&dict=eses
DEFAULT = ${google}
wiggle = http://www.wiggle.es/?s={}
arch = https://www.archlinux.org/packages/?q={}
wiki = ${wikipedia}
wr = http://www.wordreference.com/redirect/translation.aspx?w={}&dict=enen
aur = https://aur.archlinux.org/packages/?O=0&K={}
wikies = http://es.wikipedia.org/w/index.php?search={}&title=Especial:Buscar
duckduckgo = https://duckduckgo.com/?q={}
ddg = ${duckduckgo}
google = https://encrypted.google.com/search?q={}
imdb = http://www.imdb.com/find?q={}&s=all
[colors]
hints.bg = yellow
[fonts]
_monospace = monospace
hints = bold 14px sans-serif
web-family-standard = sans-serif
web-family-fixed = monospace
web-family-serif = serif
web-family-sans-serif = sans-serif
web-family-cursive = sans-serif
web-family-fantasy = sans-serif
web-size-minimum = 10
web-size-minimum-logical = 12
web-size-default = 12
web-size-default-fixed = 12

**Comment by The-Compiler** [comment] 2015-03-19 18:03
I'm afraid I still can't reproduce this, even on Arch with Qt 5.4.1.

Can you please do two things for me?

* Launch qutebrowser on the commandline with `--debug` and post the output before the crash.
* Install my Qt debug packages and produce a stack trace via gdb as [described here](https://github.com/The-Compiler/qutebrowser/blob/master/doc/stacktrace.asciidoc#crashes-which-can-be-reproduced)?

**Comment by flvi0** [comment] 2015-03-20 09:56
I can reproduce, here's a backtrace with debug symbols: http://p.cmpl.cc/b1b838fa
Since it crashes in malloc after alphaMapForGlyph, it looks suspiciously like the QFontEngineFT bug which was already reported to upstream and fix is in progress (in 5.4.2 then probably): https://bugreports.qt.io/browse/QTBUG-44812
I will retry with their patchset and see if that fixes it.

**Comment by The-Compiler** [comment] 2015-03-20 10:10
The [change](https://codereview.qt-project.org/#/c/107890) is on the 5.5 branch, so that won't make it to 5.4.2 - but will be in 5.5, [scheduled for May](http://qt-project.org/wiki/Qt-5.5-release).

**Comment by flvi0** [comment] 2015-03-20 11:45
Ok I can confirm it's the same bug, with https://codereview.qt-project.org/#/c/107890/ it does not crash anymore. And yes I meant 5.5 actually.

**Comment by The-Compiler** [comment] 2015-03-20 12:59
Closing this as it's fixed upstream and verified.

**Closed by The-Compiler** 2015-03-20 12:59 UTC
Labels: bug, can't reproduce, crash, qt
