### ISSUE TITLE
Thai fonts make statusbar too high

### ISSUE THREAD

**Issue by lahwaacz** [The-Compiler/qutebrowser#1467] opened 2016-05-01 19:31 UTC
Compare the statusbar heights on these screenshots: http://postimg.org/gallery/2aqn81lo2/
The two pages in question are [Main page](https://wiki.archlinux.org/index.php/Main_page) and [Main page (ไทย)](https://wiki.archlinux.org/index.php/Main_page_(%E0%B9%84%E0%B8%97%E0%B8%A2)) on the Arch wiki.

I'm no expert on fonts, there might be no way to fix this or it could be a problem on my side, but the HTML pages with Thai fonts are rendered OK...

**Comment by The-Compiler** [comment] 2016-05-01 20:22
Closing as a duplicate of #936

**Closed by The-Compiler** 2016-05-01 20:22 UTC
