### ISSUE TITLE
Random Screen Tearing

### ISSUE THREAD

**Issue by Jumblemuddle** [The-Compiler/qutebrowser#1234] opened 2016-01-17 14:28 UTC
I've been seeing these artifacts randomly since I installed qute on my new computer.
I have already tried running compton; no luck.
![2016-01-17-082450_1920x1080_scrot](https://cloud.githubusercontent.com/assets/3629343/12377940/2f698b7a-bcf4-11e5-8364-9202c97a912f.png)

**Comment by Jumblemuddle** [comment] 2016-01-17 14:31
`qutebrowser --version`

    qutebrowser v0.5.0
    Git commit: 
    CPython: 3.4.4
    Qt: 5.5.1, runtime: 5.5.1
    PyQt: 5.5.1

**Comment by The-Compiler** [comment] 2016-01-17 14:36
I've never seen that, seems almost like some bug in Qt and/or your graphics driver...

Any chance you could use some other Qt5 browser like Otter Browser for a while and see if it happens there as well?

**Comment by Jumblemuddle** [comment] 2016-01-17 15:09
Will do.
I don't believe it's a graphics driver issue, because it only affects the
browser. And it only begins / ends when I'm scrolling a webpage.
I'm on an Intel graphics machine, btw.

**Comment by Jumblemuddle** [comment] 2016-01-17 22:22
Finally got a chance to test otter. The tearing is still occuring.
Any ideas?
![2016-01-17-161953_1920x1080_scrot](https://cloud.githubusercontent.com/assets/3629343/12380349/80786a94-bd36-11e5-8d69-aea019075cca.png)

**Comment by lahwaacz** [comment] 2016-01-17 23:32
I assume the smooth scrolling is disabled? It should be by default in qutebrowser, but not sure about other browsers.

**Comment by Jumblemuddle** [comment] 2016-01-18 00:24
That might be it. I did enable it, just because. I'll try disabling it when
I can.

**Comment by Jumblemuddle** [comment] 2016-01-18 03:32
Unfortunately, smooth scrolling doesn't seem to be the issue.
Also, as I'm typing this message, the tearing is switching on and off just by my typing.
No screenshot; exact same as the other two.

**Comment by The-Compiler** [comment] 2016-01-18 05:16
I'm afraid I have no idea what's going on... :worried:

This definitely looks like an upstream bug, but one I've never seen. It might be resolved in the future by the new QtWebEngine backend (#666). I'm curious if it happens there as well, but I don't have anything to test (except `scripts/minimal_webkit_testbrowser.py --webengine` in the repo, but that's not a full browser, so it might be annoying to try and reproduce it there).

If it happens with QtWebEngine as well I'd ask you to [report this upstream](https://bugreports.qt.io/) (or alternatively, I can do so for you). If it doesn't, I'm afraid reporting this upstream probably means it's just going to be ignored...

I'm sorry there isn't anything else I can suggest...

**Closed by The-Compiler** 2016-01-18 05:16 UTC

**Comment by Jumblemuddle** [comment] 2016-01-19 00:47
It's ok. I didn't expect any magic fixes.
At the moment I'm not too worried about it. I may revisit it later.
Thanks for your help!
