### ISSUE TITLE
malwaredomainlist.com blocklist timing out on adblock-update

### ISSUE THREAD

**Issue by tomxtobin** [The-Compiler/qutebrowser#1180] opened 2015-12-10 17:43 UTC
I've noticed lately that one of the default blocklists, from `malwaredomainlist.com`, keeps timing out on `:adblock-update`. Testing with curl, it looks like it *does* eventually respond, but it takes over a minute:
```
$ time curl -I 'http://www.malwaredomainlist.com/hostslist/hosts.txt'
HTTP/1.1 200 OK
Date: Thu, 10 Dec 2015 17:36:21 GMT
Server: Apache/2.2.0 (Fedora)
Last-Modified: Thu, 10 Dec 2015 07:29:20 GMT
ETag: "d223-bc82-526862a4db50c"
Accept-Ranges: bytes
Content-Length: 48258
Content-Type: text/plain

curl -I 'http://www.malwaredomainlist.com/hostslist/hosts.txt'  0.00s user 0.00s system 0% cpu 1:18.44 total
```
Their webserver seems to be returning requests for other paths (e.g., `/`) at a similarly slow rate.

Is it worth keeping this blocklist in the defaults if this isn't getting resolved upstream?

**Comment by The-Compiler** [comment] 2015-12-10 20:30
I've contacted them via their contact formular - let's see if there's any reaction.

**Comment by The-Compiler** [comment] 2015-12-11 10:47
They're aware of the issue but didn't find the cause yet. Let's wait some more and see if it gets better...

**Comment by The-Compiler** [comment] 2015-12-18 19:00
The site loads quickly again for me now - can you confirm, @tomxtobin?

**Comment by tomxtobin** [comment] 2015-12-18 19:06
Yep, confirmed here.

**Comment by The-Compiler** [comment] 2015-12-18 19:07
Cool, I'm closing this then - let's hope things stay this way!

**Closed by The-Compiler** 2015-12-18 19:07 UTC
