### ISSUE TITLE
Merge equivalent hints

### ISSUE THREAD

**Issue by lamarpavel** [The-Compiler/qutebrowser#687] opened 2015-05-27 11:13 UTC
The effectiveness of the hint system depends - among other things - on the number of hints to chose from. The fewer the better.

I noticed that on pages where multiple links point to the same URL a unique hint is spawned for each link. Instead of basing the hints on links I would propose to base hints on URLs.

I see three possible implementations:

1. Several hints can share a key-mapping
2. One hint can be displayed multiple times
3. Only one link of a set with equal URLs gets a hint

Solutions 1 and 2 are different implementations of the same user experience where the number of displayed hints is the same as before but they use up fewer keys. Solution 3 would also reduce the number of hints displayed, which has the advantage of uncluttering pages with lots of links, but requires some heuristic to decide on which link to draw the hint.

**Comment by The-Compiler** [comment] 2015-05-27 11:17
Basically a duplicate of #71 - but I didn't think of 1./2. yet, I added that there. Thanks for the nice idea!

**Closed by The-Compiler** 2015-05-27 11:17 UTC

**Comment by lamarpavel** [comment] 2015-05-27 11:19
Damnit, I actually read through all issues with that tag but must have missed that one.

**Comment by The-Compiler** [comment] 2015-05-27 11:20
No worries - having ~230 open issues can be overwhelming even for myself sometimes :smile:

**Comment by flvi0** [comment] 2015-05-27 11:20
I'm not a web developer but I just reassured with my brother who is, a page can still detect which of the links was clicked using javascript and potentially behave differently even if they point to the same url, so merging them seems error-prone to me.

**Comment by The-Compiler** [comment] 2015-05-27 11:44
Hmm, that's a good point. I'll add that comment to #71. Probably will just make it configurable.

**Comment by error800** [comment] 2015-05-27 12:30
This will probably break a lot of functionality on websites. I just made a stupid example of js links :D http://codepen.io/anon/pen/gpLBvq

**Comment by The-Compiler** [comment] 2015-05-27 12:32
...I hate you. :laughing: :+1:

I wonder if it'd break less when adding some heuristics so `href`s with only an anchor get excluded from that logic.

**Comment by flvi0** [comment] 2015-05-27 12:36
My personal view on this is to keep things simple. If it can't be solved cleanly and generically, a heuristic trying to be intelligent about this asks for trouble in specific cases. I mean there can probably still be scripts parsing the whole document object model (or how that's called) structurally and not relying on an id being set. @error800?

**Comment by error800** [comment] 2015-05-27 12:36
Heheh :)
You can also put in an URL there, the e.preventDefault(); prevents the standard behaviour of the link. Example updated: http://codepen.io/anon/pen/gpLBvq

**Comment by error800** [comment] 2015-05-27 12:39
@flavio: yes thats possible, theres getElementsByTagName() and getElementsByClassName() too...

**Comment by flavio** [comment] 2015-05-27 12:40
> @flavio: yes thats possible, theres getElementsByTagName() and getElementsByClassName() too...

wrong github user :)
