### ISSUE TITLE
html5 codec problem on Windows

### ISSUE THREAD

**Issue by gregist** [The-Compiler/qutebrowser#1427] opened 2016-04-15 07:46 UTC
I am using qutebrowser v0.6.1 64bit on Windows 10. (installed using pre-compiled binaries on releases page.)

Twitter video is not working,

![qutebrowser_2016-04-15_15-25-06](https://cloud.githubusercontent.com/assets/6292095/14554395/4d096a3a-031f-11e6-9bdd-9787e0613152.png)

here is the test result on html5test.com,

![qutebrowser_2016-04-15_15-36-42](https://cloud.githubusercontent.com/assets/6292095/14554491/f388583a-031f-11e6-8c7f-4f4530330323.png)

Html5 videos work fine on Chrome/FF on the same system. Is it a known bug or what?

**Comment by The-Compiler** [comment] 2016-04-15 07:51
QtWebKit on Windows unfortunately is quite bad when it comes to video support. #1068 *might* make this better, but I'm not sure.

Either way, things are probably going to look much better in the future with QtWebEngine (there's [a crowdfunding running currently](http://igg.me/at/qutebrowser) to add support for that!).

Things you could try:

- Does it work better with [QupZilla](http://qupzilla.com/) or [Otter Browser](http://otter-browser.org/) (not the QtWebEngine version)?
- Does anything change when you install a codec pack like [CCCP](http://cccp-project.net/) or [K-Lite](http://codecguide.com/download_kl.htm)?

**Comment by gregist** [comment] 2016-04-15 08:23
Thanks for the quick reply! I installed the latest otter browser and it works. It is using webkit also.

![otter-browser_2016-04-15_16-19-27](https://cloud.githubusercontent.com/assets/6292095/14555599/1e298036-0326-11e6-822d-ef2e1abaf194.png)

No, installing a codec pack won't help. I have tried both.

**Comment by The-Compiler** [comment] 2016-04-15 08:24
Does it work if you do `:set content allow-plugins true` in qutebrowser?

**Comment by gregist** [comment] 2016-04-15 08:29
No. 

This setting enables flash playback though. I can now watch youtube. Webm still not supported.

**Comment by gregist** [comment] 2016-04-15 08:29
No. 

This setting enables flash playback though. I can now watch youtube. Webm still not supported.

**Comment by gregist** [comment] 2016-04-15 08:29
No. 

This setting enables flash playback though. I can now watch youtube. Webm still not supported.

**Comment by gregist** [comment] 2016-04-15 08:29
No. 

This setting enables flash playback though. I can now watch youtube. Webm still not supported.

**Comment by gregist** [comment] 2016-04-15 08:30
No. 

This setting enables flash playback though. I can now watch youtube. Webm still not supported.

**Comment by The-Compiler** [comment] 2016-04-15 08:38
If you sent your comment multiple times because of the GitHub page not refreshing: Set the user-agent back to the default, otherwise GitHub breaks. That'll be fixed by QtWebEngine too.

Could you please make sure you downloaded qutebrowser/Otter with the same architecture (32/64bit), and then try copying the following folders from the Otter directory to where qutebrowser is installed?

- audio
- bearer
- iconengines
- mediaservice
- printsupport

If that changes things, what I suspected in #1068 will improve things indeed.

**Comment by gregist** [comment] 2016-04-15 09:06
Haha thanks, I was wondering why.

made the change, qutebrowser now crashes when I try to play twitter videos. Guess it's an improvement. :smile: 

I have sent you the crash report on crash@qutebrowser.org , hope it helps.

**Comment by The-Compiler** [comment] 2016-04-15 09:07
Hmm. I'll look into it whenever I happen to be on a Windows machine again. Might take me a while though. Thanks for all the testing!

**Comment by The-Compiler** [comment] 2016-08-01 19:43
Seems like it works with the DLLs I [got from my build machine](https://www.qutebrowser.org/tmp/dlls.zip) for others. I'm closing this as a duplicate of #1068 then.

**Closed by The-Compiler** 2016-08-01 19:43 UTC
Labels: os: windows, priority: 1 - middle
