### ISSUE TITLE
Fragment jump incorrect when opening tab in background

### ISSUE THREAD

**Issue by rcorre** [The-Compiler/qutebrowser#1417] opened 2016-04-11 01:47 UTC
1. Open to http://doc.qt.io/qt-5/qurl.html#matches in a background tab
2. Wait until the tab loads
3. Switch to the tab

Note that the page has scrolled all the way to the bottom instead of to `matches`.
Now try again, but switch to the tab right after you open it in the background. If you do it fast enough, it will jump to the fragment as you would expect. It seems to work in a chromium background tab no matter how long I wait.

**Comment by The-Compiler** [comment] 2016-04-11 04:38
Duplicate of #1190 - but you just found out how to reliably reproduce it, which is very useful!

**Closed by The-Compiler** 2016-04-11 04:38 UTC
