### ISSUE TITLE
Grey bar right below the tabs

### ISSUE THREAD

**Issue by yuhuanq** [The-Compiler/qutebrowser#1693] opened 2016-07-28 06:06 UTC
Any idea what this grey bar right below the tabs is? Supposed to be there and configurable? It's covering the top of webpages.

[scrnsht](http://i.imgur.com/Ja0vsGj.png)
---
Fedora 24

qutebrowser v0.7.0

CPython: 3.5.1
Qt: 5.6.1, runtime: 5.6.1
PyQt: 5.6

**Comment by The-Compiler** [comment] 2016-07-28 06:10
Hmm, that's odd - that looks like for some reason Qt thinks the tabbar needs more space than it actually does.

What desktop environment/theme/... is this with? Do you also see it when you start with `--temp-basedir`?

**Comment by yuhuanq** [comment] 2016-07-28 06:39
Still there even with `--temp-basedir`. On GNOME 3.20, tried switching GTK/shell themes, same result. Latest version is however working perfectly on a lubuntu vm.

**Comment by lahwaacz** [comment] 2016-07-28 06:50
Last time I heard 3.20, it was [GTK+ breaking Firefox](https://wiki.archlinux.org/index.php?title=Firefox&type=revision&diff=443425&oldid=441642), but since qutebrowser uses Qt, maybe it has problems with the other G...

**Comment by ploz** [comment] 2016-08-20 16:59
Under Arch, having the aur package `adwaita-qt5` installed seems to cause this issue. See if uninstalling the corresponding Fedora package (which I believe is named the same thing) fixes this for you.

**Comment by ploz** [comment] 2016-08-20 16:59
Under Arch, having the aur package `adwaita-qt5` installed seems to cause this issue. See if uninstalling the corresponding Fedora package (which I believe is named the same thing) fixes this for you.

**Comment by ploz** [comment] 2016-08-20 16:59
Under Arch, having the aur package `adwaita-qt5` installed seems to cause this issue. See if uninstalling the corresponding Fedora package (which I believe is named the same thing) fixes this for you.

**Comment by The-Compiler** [comment] 2016-08-20 17:08
Reproduced after doing that, installing `qt5ct`, setting `QT_QPA_PLATFORMTHEME=qt5ct` and choosing adwaita in qt5ct. Not sure if qutebrowser can do anything about this...

**Comment by The-Compiler** [comment] 2016-08-20 17:10
It seems to take the color of `colors -> tabs.bg.bar` FWIW

**Comment by The-Compiler** [comment] 2016-08-20 18:43
No luck getting rid of it so far - I opened https://github.com/MartinBriza/adwaita-qt/issues/45

**Comment by rokm** [comment] 2016-08-29 12:12
This seems to be an issue with qutebrowser's custom styling, rather than adwaita; even though adwaita may be the only style with widget sizes that cause this issue to manifest...

The core issue is that even with the custom style, Adwaita::subElementRect() gets called for SE_TabWidgetTabBar, which returns rects with style-specific height of 35 - the same as the height of the offedning gray area.

It seems that these calls come from the Qt's QTabWidget code that sets up the layout (i.e., QTabWidget::setUpLayout()).

So I'd say the actual issue here is two-fold:

a) qutebrowser sets custom style only on tab bar, but not on tab widget - so layout setup ends up operating with adwaita style sizes instead of the custom ones that are used for actual rendering.

b) TabBarStyle.subElementRect forwards the call for SE_TabWidgetTabBar to self._style (= adwaita) instead of super(), which, on the other hand, is used to render CE_TabBarTabShape in drawControl().

Addressing these two issues seems to deal away with the gray area for me.

**Comment by The-Compiler** [comment] 2016-08-29 12:23
#1901 seems to fix this for me indeed - thanks a lot! @yuhuanq @ploz can you confirm?

**Comment by ploz** [comment] 2016-08-31 04:55
Black bar still occurs when `adwaita-qt5` package is installed and:
- qt5ct is not active
- qt5ct is active and theme is set to adwaita

**Comment by The-Compiler** [comment] 2016-08-31 04:57
@ploz are you testing with the latest `master` or with the branch from #1901? I haven't merged it yet, I'm a bit short on time currently :wink:

**Comment by The-Compiler** [comment] 2016-09-01 05:30
Assuming #1901 fixes this, which is now merged.

**Closed by The-Compiler** 2016-09-01 05:30 UTC
Labels: bug, component: ui, priority: 2 - low

**Comment by ploz** [comment] 2016-09-14 01:14
I was testing with latest master, can confirm that #1901 fixes for me.
