### ISSUE TITLE
Hint target (fg/bg) is being overridden by some websites

### ISSUE THREAD

**Issue by boblehest** [The-Compiler/qutebrowser#676] opened 2015-05-18 21:59 UTC
https://rust.zeef.com/harris.brakmic

On this website, the listed links are always opened in a new foreground tab, regardless of whether you use a hint target to open in current tab or a background tab.

**Comment by lahwaacz** [comment] 2016-02-21 09:16
Since hinting works by emulating click events, the behaviour should be the same as clicking the links with a mouse. Websites can certainly force to open a link in a new tab when it is left-clicked, so this is no problem. The problem is that generally `Ctrl+LeftClick != MiddleClick` (qutebrowser uses `Ctrl+LeftClick` for the background tab target). Specifically on the website reported by @boblehest, middle-click opens the links in a new background tab as expected, but `Ctrl+LeftClick` opens it in a new foreground tab.

**Comment by paretje** [comment] 2016-03-25 14:01
Does that mean there is, currently, no way to force URL's to open in the current tab? Currently, I have  this in `keys.conf`:
```
hint links run open {hint-url}
    f
```
But, that doesn't work well if the URL triggers some javascript, or if you want to click a button.

**Comment by The-Compiler** [comment] 2016-03-25 16:20
@paretje Indeed - and that's exactly why qutebrowser emulates a click rather than getting/opening the URL.

**Comment by paretje** [comment] 2016-03-26 15:38
@The-Compiler: I did a quick search and am I right to conclude that the html is never loaded in python, but is handled by Qt/QtWebKit, and so it isn't really possible to do something like [VimFX](https://github.com/akhodakivskiy/VimFx/blob/master/extension/lib/commands-frame.coffee#L292) does in qutebrowser?

It could be done using jseval and autocmd's I guess, but with QtWebKit, I would have to enable javascript everywhere, and I don't want that.

**Comment by The-Compiler** [comment] 2016-03-27 21:31
It uses the [QWebElement API](http://doc.qt.io/archives/qt-5.5/qwebelement.html) (`qutebrowser/browser/webelem.py`) so this might actually be possible. I also think I found a loophole which allows me to execute JS even if disabled, but still need to make sure this actually works everywhere.

**Comment by paretje** [comment] 2016-03-27 21:43
Sounds great!

**Comment by The-Compiler** [comment] 2016-11-16 06:19
This was fixed in #1381.

**Closed by The-Compiler** 2016-11-16 06:19 UTC
Labels: component: hints, priority: 1 - middle
