### ISSUE TITLE
Command/Windows key not respected?

### ISSUE THREAD

**Issue by fosskers** [The-Compiler/qutebrowser#420] opened 2014-12-27 23:25 UTC
I have my window manager's Meta key set to my `command` key (Linux on a Mac). I switch between input modes using `command + i`. A few things I've noticed:

1. When in insert mode, typing `command + i` just inserts an `i`.
2. When not in insert mode, typing `command + i` brings me into insert mode.
3. When typing in a form where `ctrl + i` is recognized (for italics, etc), typing `command + i` is recognized as if it were `ctrl + i`.

Any clues?

**Comment by The-Compiler** [comment] 2015-03-05 06:48
Sorry for the long delay!

I just noticed some code which might be responsible for this (though I doubt it, but it's worth a try).

Can you please check if the issue is gone in the [issue420](https://github.com/The-Compiler/qutebrowser/tree/issue420) branch? And can you also verify if it still works right on OS X, if you use that as well?

**Comment by fosskers** [comment] 2015-03-06 06:50
I'll take some time on the weekend to test this out.

**Comment by The-Compiler** [comment] 2015-03-06 06:53
Also, do you use something like `xmodmap`/`xbindkeys`? I think (at least in older versions), Qt didn't respect xmodmap.

**Comment by fosskers** [comment] 2015-03-06 07:15
I use `uim` actually.

**Comment by fosskers** [comment] 2015-03-08 23:19
So I'm an Arch user, the laptop just happens to be a Mac. I cloned the repo and tested things, and the same problem persists. I then took a look at the relevant commit, and noticed it would only affect things should `sys.platform` return `darwin`.

**Comment by The-Compiler** [comment] 2015-05-16 11:03
Sorry again for the delay and thanks for the reminder in #661 :wink:. It's sometimes hard to keep up with issues which don't affect me personally and might be upstream Qt bugs.

I recently added a small tool which outputs the received keys - could you please clone/pull the repo, then run `python3 -m scripts.keytester`, press `command + i` and show me the info it shows?

Then could you please try with the Qt 5.5 beta from my `qt-debug` repo? See [this doc](https://github.com/The-Compiler/qutebrowser/blob/master/doc/stacktrace.asciidoc#archlinux) (under "To install my pre-built packages") and then do something like:

`pacman -S qt5-connectivity-beta qt5-declarative-beta qt5-enginio-beta qt5-imageformats-beta qt5-location-beta qt5-multimedia-beta qt5-quick1-beta qt5-quickcontrols-beta qt5-script-beta qt5-sensors-beta qt5-serialport-beta qt5-svg-beta qt5-tools-beta qt5-wayland-beta qt5-webchannel-beta qt5-webengine-beta qt5-websockets-beta qt5-x11extras-beta qt5-xmlpatterns-beta qt5-webkit-beta qt5-base-beta`

(probably not all of those modules are needed, but other Qt software will stop working if you update `qt5-base` to the beta version but not the rest).

**Comment by The-Compiler** [comment] 2015-05-17 17:15
I've now fixed a similiar issue on OS X in 10985c3 because [Qt swaps Ctrl and Meta](http://doc.qt.io/qt-5.4/osx-issues.html#special-keys) on OS X:

> To provide the expected behavior for Qt applications on OS X, the Qt::Meta, Qt::MetaModifier, and Qt::META enum values correspond to the Control keys on the standard Apple keyboard, and the Qt::Control, Qt::ControlModifier, and Qt::CTRL enum values correspond to the Command keys.

I wonder if something similiar happens for you because it's a Mac laptop/keyboard.

**Comment by fosskers** [comment] 2015-05-18 04:39
Arch Linux seems to recognize the Mac `command` key as the linux "super" key.

**Comment by The-Compiler** [comment] 2015-05-18 04:44
Okay, and what does this show up as in the keytester? I'd expect `Meta` and `Meta-i`. But it's all rather weird... if you bound this in your WM, I'd expect it to never reach Qt at all.

**Comment by fosskers** [comment] 2015-05-19 06:07
I will let you know once I have the keytesting environment set up.

**Comment by fosskers** [comment] 2015-05-19 06:13
With just `command` it shows
```
None
key: 0x100022
modifiers: 0x10000000
text: "
```
With `command + i`:
```
Meta+I
key: 0x49
modifiers: 0x10000000
text: 'i'
```

**Comment by The-Compiler** [comment] 2015-05-19 06:48
Okay, that looks like what I'd expect.

You should be able to switch input methods with a simple line edit, right? Let's try this:

`python3 -c 'from PyQt5.QtWidgets import QApplication, QLineEdit; app = QApplication([]); le = QLineEdit(); le.show(); app.exec_()'`

If it works there, it's something I can probably fix in qutebrowser. If not, it's some kind of a Qt bug - then maybe try again when Qt 5.5 is out (or install the `-beta` packages from my `qt-debug` [repo](https://github.com/The-Compiler/qutebrowser/blob/master/doc/stacktrace.asciidoc#archlinux)) and if it's still broken there, [open a Qt bug](https://bugreports.qt.io/).

**Comment by fosskers** [comment] 2015-05-19 16:17
It still types the `i` character, unfortunately.

**Comment by The-Compiler** [comment] 2015-06-01 08:17
Meh :worried:

Can you please [open a Qt bug](https://bugreports.qt.io/secure/Dashboard.jspa) and link it here - it seems this is definitely not something I can fix in qutebrowser.

(I'd usually do this for you, but here I just lack all the background information, so I think it's better if you do it).

Sorry I can't do anything else!

**Closed by The-Compiler** 2015-06-01 08:17 UTC
Labels: bug, component: keyinput
