### ISSUE TITLE
Can't get qutebrowser to start

### ISSUE THREAD

**Issue by shankargopal** [The-Compiler/qutebrowser#532] opened 2015-03-05 10:18 UTC
This is obviously a very basic issue, but I've followed the instructions for an install on Debian Jessie.  When I finish I run:

    /home/user/Software/qutebrowser-master/.venv/bin/python3 -m qutebrowser

which is the correct directory.  And I get:

    /home/user/Software/qutebrowser-master/.venv/bin/python3: No module named qutebrowser

I've programmed in python myself but I can't seem to figure out this problem!  Apologies, I know the answer must be something very simple.

Thanks for all of your work!

**Comment by The-Compiler** [comment] 2015-03-05 10:26
So you did run `setup.py`, and also did so with the virtualenv python?

Do you see qutebrowser-related things in `.venv/lib/python3.4/site-packages`? Do you have `$PYTHONPATH` or `$PYTHONHOME` set to something strange in your environment?

**Comment by shankargopal** [comment] 2015-03-05 10:48
> So you did run `setup.py`, and also did so with the virtualenv python?

I haven't used distutils, and can't quite follow.  After this message I did run setup.py from qutebrowser-master now with python3 and it completed successfully.  However, I still get the same error.  What do you mean by "with the virtualenv python"?  There is no setup.py in the .venv/bin directory, and when I try to run "./python3 ../../setup.py" from there I get other errors. 


> Do you see qutebrowser-related things in
> `.venv/lib/python3.4/site-packages`? Do you have `$PYTHONPATH` or
> `$PYTHONHOME` set to something strange in your environment?
> 

Both PYTHONPATH and PYTHONHOME are empty.  I have qutebrowser.egg-link in .venv/lib/python3.4/site-packages .

**Comment by The-Compiler** [comment] 2015-03-05 10:55
> > So you did run `setup.py`, and also did so with the virtualenv python?
> 
> I haven't used distutils, and can't quite follow.  After this message I did run setup.py from qutebrowser-master now with python3 and it completed successfully.  However, I still get the same error.  What do you mean by "with the virtualenv python"?  There is no setup.py in the .venv/bin directory, and when I try to run "./python3 ../../setup.py" from there I get other errors. 

A virtualenv is essentially a separate Python installation - so if you run setup.py with your system's python, qutebrowser will not be installed inside the virtualenv.

Try running something like this from the repositories root:

`./.venv/python3 setup.py install`

> > Do you see qutebrowser-related things in
> > `.venv/lib/python3.4/site-packages`? Do you have `$PYTHONPATH` or
> > `$PYTHONHOME` set to something strange in your environment?
> > 
> 
> Both PYTHONPATH and PYTHONHOME are empty.  I have qutebrowser.egg-link in .venv/lib/python3.4/site-packages .

Okay, that's the same I'm seeing here as well. So I don't see why this won't work... You should also have a `.venv/bin/qutebrowser`, can you try running that?

What happens if you run `./venv/bin/python3` and do `import qutebrowser` in the interactive interpreter?

**Comment by shankargopal** [comment] 2015-03-05 11:08
> A virtualenv is essentially a separate Python installation - so if
> you run setup.py with your system's python, qutebrowser will not be
> installed inside the virtualenv.
> 
> Try running something like this from the repositories root:
> 
> `./.venv/python3 setup.py install`
> 

That did it, thanks!  Now it starts.  Might be worth adding this bit to the install instructions?

Thanks again for all of your work - I'm now looking forward to using qutebrowser full time :)

**Comment by The-Compiler** [comment] 2015-03-05 12:13
Actually this is confusing... When you run `init_venv.py` it should run that for you, I just didn't remember because I didn't use it for some while ;)

Can you try to delete `.venv` and reproduce the issue again, with just running `init_venv.py` and then trying to run qutebrowser? I just tried again on Debian Jessie and it works fine here, so I wonder what was different in your case.

> Thanks again for all of your work - I'm now looking forward to using qutebrowser full time :)

You're welcome! Glad to hear that! :)

**Comment by shankargopal** [comment] 2015-03-05 12:25
On Thu, 05 Mar 2015 04:13:56 -0800
Florian Bruhin <notifications@github.com> wrote:

> Actually this is confusing... When you run `init_venv.py` it should
> run that for you, I just didn't remember because I didn't use it for
> some while ;)
> 
> Can you try to delete `.venv` and reproduce the issue again, with
> just running `init_venv.py` and then trying to run qutebrowser? I
> just tried again on Debian Jessie and it works fine here, so I wonder
> what was different in your case.

I did that, and this time it worked?!  I don't get it.  I followed the instructions quite closely the first time around as well.  I didn't have setuptools installed for python3 - maybe that was the problem?

**Comment by The-Compiler** [comment] 2015-03-05 12:30
Weird. Actually `init_venv.py` should work without setuptools installed, as it [bootstraps it via get-pip.py](https://github.com/The-Compiler/qutebrowser/blob/master/scripts/init_venv.py#L186-L196) if it's unavailable.

No idea what happened there. I have [buildbots running](http://qutebrowser.org:8010/waterfall) which use `init_venv.py` automatically several times per day on Debian Jessie (and Ubuntu too), and there never was any issue. Either way, I'm closing this, and glad it works now :)

**Closed by The-Compiler** 2015-03-05 12:30 UTC
