### ISSUE TITLE
I can't play HTLM5 video 

### ISSUE THREAD

**Issue by LaVolte** [The-Compiler/qutebrowser#1655] opened 2016-07-15 21:52 UTC
Hi, I'm using qutebrowser on Windows 10 and I can't play HTLM5 video. For exemple I can't play any video on youtube. I use mpv for the moment. 

I've attached the result of qute:version and a dxdiag.

You maybe need more informations to solve/recreate this issue ? 

Thank you a lot for this amazing web browser by the way !

[quteversion.txt](https://github.com/The-Compiler/qutebrowser/files/366895/quteversion.txt)
[DxDiag.txt](https://github.com/The-Compiler/qutebrowser/files/366896/DxDiag.txt)
"an error occurred, please try again later."
![untitled](https://cloud.githubusercontent.com/assets/18049177/16889578/c369266a-4ae7-11e6-9d90-4067d60568d0.jpg)

---

**Comment by The-Compiler** [comment] 2016-07-25 13:05
Sorry for the late answer! I know some other people with similar problems on Windows, but I haven't really had time to investigate yet.

Some things which *could* help:

- Copying some missing Qt DLLs in your qutebrowser folder, see #1068. The best place to get them would probably be a Qt 5.5 installer.
- Installing some codec pack like [K-Lite](http://codecguide.com/) or CCCP](http://cccp-project.net/)

**Comment by LaVolte** [comment] 2016-07-25 13:25
Thank you for your answer.

 I'll try the two points you've suggested and report to you if it helps.

Keep up the good work !

**Comment by LaVolte** [comment] 2016-07-25 13:54
I've install the CCCP pack and nothing changed.

I've also added the ddl, respecting the folder structure : 

• audio/qtaudio_windows.dll 
• iconengines/qsvgicon.dll 
• mediaservice/wmfengine.dll 
• printsupport/windowsprintersupport.dll 

Now the player layout is fonctionnal (I can choose quality etc.), the video load and the browser crash, showing this message : 
![ezr](https://cloud.githubusercontent.com/assets/18049177/17103682/d0bbf8ac-527f-11e6-9f67-34babdb43a4e.png)

Sometimes it fallback to flashplayer, the video play but I can't interact with the layout.

**Comment by The-Compiler** [comment] 2016-07-25 13:56
Can you try with [Otter Browser](https://otter-browser.org/) please? (With the normal version, not the QtWebEngine one). Unfortunately it's unlikely there's much I can do until QtWebEngine support is working...

**Comment by LaVolte** [comment] 2016-07-25 14:19
The QtWebKit version works perfectly, I had no problem with HTML5.

I understand concerning the QtWebEngine and I can't wait to try it out !

**Comment by The-Compiler** [comment] 2016-07-25 14:20
Hmm, that's odd - and you got the DLLs from a 64bit Qt 5.5.1?

**Comment by LaVolte** [comment] 2016-07-25 14:42
Yes, I've even tried by copying the following dll from otter browser 64  to qutebrowser : 

• audio/qtaudio_windows.dll 
 • iconengines/qsvgicon.dll 
 • mediaservice/wmfengine.dll 
 • printsupport/windowsprintersupport.dll 

It's the same as before, the layout works perfectly, the video load but then the browser crash.

**Comment by JohnMurga** [comment] 2016-07-31 17:46
Same problem here ...
Regular weekly builds of Otter do HTML5 video well for me ...
However, coping the DLLs crashes qutebrowser as it appears that the Otter ones are built against a much newer version of the msvc* DLLs.

**Comment by The-Compiler** [comment] 2016-08-01 09:00
I just zipped up the DLLs from my build machine: [dlls.zip](https://www.qutebrowser.org/tmp/dlls.zip) - can you verify whether things work better with those? If yes, I'll make sure they're correctly packaged with the next release.

**Comment by UltraSabreman** [comment] 2016-08-01 19:14
Yep those DLLs fixed the issue for me. Thank you!

**Comment by The-Compiler** [comment] 2016-08-01 19:42
Closing this as a duplicate of #1068 then. Thanks for the testing!

**Closed by The-Compiler** 2016-08-01 19:42 UTC
Labels: os: windows, priority: 2 - low, qt, QtWebEngine

**Comment by jujey** [comment] 2020-02-25 02:47
2020, still can't play MPEG/MP4 videos, like live streams.

**Comment by jujey** [comment] 2020-02-25 02:47
this was fine on Linux but not working on a fresh Windows 10 installation

**Comment by The-Compiler** [comment] 2020-02-25 07:13
@jujey From the [install instructions](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#prebuilt-binaries):

> The binary release ships with a QtWebEngine built without proprietary codec support. To get support for e.g. h264/h265 videos, you’ll need to build QtWebEngine from source yourself with support for that enabled.
