### ISSUE TITLE
bloomberg.com freezes qutebrowser

### ISSUE THREAD

**Issue by MazeChaZer** [The-Compiler/qutebrowser#775] opened 2015-06-20 16:45 UTC
When I try to navigate to

http://www.bloomberg.com/news/articles/2015-06-16/the-creator-of-linux-on-the-future-without-him

qutebrowser freezes after loading ~66% of the page. The CPU usage goes up, too.

Looks like an upstream bug on first sight.

**Comment by The-Compiler** [comment] 2015-06-20 17:02
Works fine for me.

What Qt version are you on? (See `:open qute:version`).

Does `:set content allow-plugins false` change anything? What about `allow-javascript`?

If you start qutebrowser with `--debug` in a terminal, do you see anything suspicious in the log when it's loading?

**Comment by MazeChaZer** [comment] 2015-06-21 15:46
I am using the most current qutebrowser-git package from the AUR.

`:open qute:version` yields

```
qutebrowser v0.2.1
Git commit: v0.2.0-551-g4dd23c5 (2015-06-20 13:09:32 +0200)

CPython: 3.4.3
Qt: 5.4.2, runtime: 5.4.2
PyQt: 5.4.2
sip: 4.16.8
colorlog: no
colorama: 0.3.3
pypeg2: 2.15
jinja2: 2.7.3
pygments: 2.0.2
yaml: 3.11
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2c 12 Jun 2015

Frozen: False
Platform: Linux-4.0.5-1-ARCH-x86_64-with-arch, 64bit
OS Version: arch

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"



--- /etc/arch-release ---
```

Disabling plugins or javascript does not help.

When I start qutebrowser with the `--debug`-flag, this is the output on the command line:

http://pastebin.com/D46ThZuM

**Comment by The-Compiler** [comment] 2015-06-22 19:12
I have no idea why this is happening and why it works for me :wink:

Can you send a `SIGUSR1` to the process and watch the output in the console? If that just shows `qt_mainloop`, can you install gdb, do something like `gdb /usr/bin/python3 -ex 'run -m qutebrowser'` and then press ctrl-c and do `bt` when it's hanging?

**Comment by MazeChaZer** [comment] 2015-06-22 19:42
If I send a `SIGUSR1` signal this is printed

```
Current thread 0x00007fb71f70d700 (most recent call first):
  File "/usr/lib/python3.4/site-packages/qutebrowser/app.py", line 127 in qt_mainloop
  File "/usr/lib/python3.4/site-packages/qutebrowser/app.py", line 117 in run
  File "/usr/lib/python3.4/site-packages/qutebrowser/qutebrowser.py", line 149 in main
  File "/usr/bin/qutebrowser", line 9 in <module>
```

Output of `bt`: http://pastebin.com/S4BenBJd

**Comment by The-Compiler** [comment] 2015-06-22 20:15
Odd... if you reproduce it a few times, does the backtrace always point there?

If you wait some minutes, is it still stuck?

**Comment by Permafacture** [comment] 2015-06-25 16:13
With javascript, that page freezes qute for me too.  But turning off javascript fixes it.  

It's scrolling down the page that triggers the freeze for me, where the second story gets loaded, probably through ajax (that story isn't there without javascript).  Also, one can't turn off javascript in the `qute:settings` because that page uses javascript, so it must be turned off with the command `:set content allow-javascript false`

**Comment by MazeChaZer** [comment] 2015-06-25 18:45
Waiting doesn't help for me, the browser is still frozen after 5 minutes.
The backtraces differs each time, but it always points to font-related stuff.

Backtrace after 5 minutes: http://pastebin.com/mehstu91
Another backtrace: http://pastebin.com/fp4QdTP2

**Comment by Permafacture** [comment] 2015-06-25 19:29
Are you certain javascript is disabled?  There's no ads, the video doesn't
play, and when you scroll down there's no Obama story?  I only ask because
it's weird that disabling javascript solves it for me but not for you.

**Comment by MazeChaZer** [comment] 2015-06-25 21:00
I just double-checked and yes, I'm sure javascript is disabled.
The page freezes immediately, this is a screenshot how I see it: http://i.imgur.com/fSkdvIj.png
Strangely I don't have problems viewing the page on my laptop although the output of `qute:version` is exactly the same on both machines except for the `Desktop` value.

**Comment by The-Compiler** [comment] 2015-06-25 21:35
Yeah, I'm still unable to reproduce this as well.

I wonder if it's something fixed in Qt 5.5, as there were various font rendering improvements/bugfixes there - so you can either wait until it's released (a week until the official release and some days for Archlinux to catch up), or if you feel adventurous you can [activate my repo](https://github.com/The-Compiler/qutebrowser/blob/master/doc/stacktrace.asciidoc#archlinux) and then install the `qt5-*-beta` package for all `qt5-*` packages you have installed (except -docs and -examples).

**Comment by MazeChaZer** [comment] 2015-06-27 11:30
Ok, thanks, I'm going to wait for the official release then. I do feel adventurous normally, but I don't have much time at the moment ;)

**Comment by The-Compiler** [comment] 2015-07-13 04:17
Qt 5.5 is out in the meantime - can you please test with that again, @MazeChaZer?

**Comment by The-Compiler** [comment] 2015-07-13 08:48
Sorry - I just noticed Qt 5.5 is only in `[testing]` for the moment on Arch - so we'll have to wait some more days until it hits `[extra]`.

**Comment by The-Compiler** [comment] 2015-07-16 19:10
Okay, *now* 5.5 should be out :smile: Can you please test, @MazeChaZer?

**Comment by MazeChaZer** [comment] 2015-07-16 21:55
Sure thing, will test it tomorrow.

**Comment by MazeChaZer** [comment] 2015-07-17 18:57
I just did the upgrade to Qt 5.5, but the issue is still there. Although PyQt is still on version 5.4.2, quite:version says
    Qt: 5.4.2, runtime: 5.5.0
    PyQt: 5.4.2

**Comment by The-Compiler** [comment] 2015-07-17 19:26
Bummer... can you try `scripts/minimal_webkit_testbrowser.py http://www.bloomberg.com` and see if it happens there as well? Also, can you install `qt5-webengine` and check with the same script with `--webengine`?

The version is okay - `Qt` says which Qt version PyQt was compiled against.

**Comment by madc0de** [comment] 2015-07-17 20:44
I was having the same problem, i think i found the fix.

First i updated Qt to 5.5 as advised, then reinstalled qutebrowser-git from AUR. After that i ran qutebrowser with --basedir for a fresh configration. Unfortunately it froze again. I pressed Ctrl+C, and it threw out this message: "Please close browser and run mozplugger-update"

Freezing started happening after i removed some unused packages, including mozplugger. I reinstalled it, and freezing is now gone.

**Comment by The-Compiler** [comment] 2015-07-17 21:37
Oooh, the mozplugger thing, I remember that now... I think you can also delete some file/dir (`~/.mozplugger` or so?) which is left behind when mozplugger is uninstalled.

**Comment by MazeChaZer** [comment] 2015-07-19 15:27
Using the `scripts/minimal_webkit_testbrowser.py` script resulted in the same freeze as before, but using `scripts/minimal_webkit_testbrowser.py --webengine` fixed the problem for me!
@madc0de I checked the console output again, and there was no error message about mozplugger in my case, I am pretty sure I never had it installed, there was `.mozplugger` folder in my home directory neither.

**Comment by MazeChaZer** [comment] 2015-07-19 15:29
One more update: I just uninstalled the `ttf-google-fonts-git` package, and the issue is also gone now! This explains why it worked on my laptop, I had not installed the package there yet.

**Comment by The-Compiler** [comment] 2015-08-04 21:55
Since this seems to be a QtWebKit bug and bugreports for it will most likely be ignored (as it's deprecated) I'm closing this. Stay tuned to #666! :wink:

**Closed by The-Compiler** 2015-08-04 21:55 UTC
Labels: report upstream
