### ISSUE TITLE
"Û" Character When Escape with Ctrl-[

### ISSUE THREAD

**Issue by springcold** [The-Compiler/qutebrowser#1329] opened 2016-03-02 13:23 UTC
**Reproduced by**

1. Focus on textbox (Goes into insert mode)
2. Press Ctrl-[ (Exit insert mode)
3. Press Ctrl-[ again ("Û" is printed on the textbox)

**Expected Behavior**
instead of "Û" printed, cursor should be remove off textbox (Same as of pressing `<esc>`)

**Comment by The-Compiler** [comment] 2016-03-02 13:34
I can't reproduce this - what text box are you seeing this in, and with what Qt/PyQt version (see `:open qute:version`)

**Comment by springcold** [comment] 2016-03-02 14:38
Version 5.5.1, I have included other information in case you need them
```
qutebrowser v0.5.1
Git commit: 

CPython: 3.5.1
Qt: 5.5.1, runtime: 5.5.1
PyQt: 5.5.1
Style: QMacStyle
Desktop: None
sip: 4.17
colorlog: no
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.2
yaml: 3.11
cssutils: no
pdf.js: no
Webkit: 538.1
Harfbuzz: system
SSL: Secure Transport, OS X El Capitan (10.11)

Frozen: False
Platform: Darwin-15.3.0-x86_64-i386-64bit, 64bit
OS Version: 10.11.3, x86_64
```

**Comment by The-Compiler** [comment] 2016-03-02 14:40
Can you confirm you're on OS X 10.11? Also, can you link to some page where you see this, so I can be sure I'm trying to reproduce this correctly?

**Comment by springcold** [comment] 2016-03-02 14:43
You can try the textbox in [duckduckgo.com](url) and yes, I am on OS X 10.11

**Comment by The-Compiler** [comment] 2016-03-02 14:45
Okay, I definitely can't reproduce this here on Linux, and it'll probably take a while until I can check on OS X.

Could you please start a new instance with `qutebrowser --temp-basedir duckduckgo.com`, reproduce the issue, and then do `:report` and submit a debug log? That might help tracking it down.

**Comment by springcold** [comment] 2016-03-02 14:50
Done, I have added in the report to point to #1329 for details. That should provide easy tracking I hope

**Comment by The-Compiler** [comment] 2016-03-02 14:55
Thanks! Nothing really interesting unfortunately:

```
webview    webview:_set_load_status:182 load status for <qutebrowser.browser.webview.WebView tab_id=0 url='https://duckduckgo.com/'>: LoadStatus.success_https
modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
keyboard   basekeyparser:_debug_log:107 Ignoring only-modifier keyeevent.
keyboard   basekeyparser:_debug_log:107 Got key: 0x1000022 / text: ''
keyboard   basekeyparser:_debug_log:107 Ignoring, no text char
modes      modeman:_eventFilter_keypress:197 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab False --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=0 url='https://duckduckgo.com/'>)
modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
keyboard   basekeyparser:_debug_log:107 No binding found for ctrl+[.
keyboard   basekeyparser:_debug_log:107 Got key: 0x5b / text: ''
keyboard   basekeyparser:_debug_log:107 Ignoring, no text char
modes      modeman:_eventFilter_keypress:197 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab False --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=0 url='https://duckduckgo.com/'>)
modes      modeman:_eventFilter_keyrelease:217 filter: False
modes      modeman:_eventFilter_keyrelease:217 filter: False
modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
keyboard   basekeyparser:_debug_log:107 Ignoring only-modifier keyeevent.
keyboard   basekeyparser:_debug_log:107 Got key: 0x1000020 / text: ''
keyboard   basekeyparser:_debug_log:107 Ignoring, no text char
modes      modeman:_eventFilter_keypress:197 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab False --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=0 url='https://duckduckgo.com/'>)
```

**Comment by The-Compiler** [comment] 2016-05-04 20:46
I can reproduce this on OS X, but I think it's a duplicate of #1258.

This is what happens:

- `Ctrl-[` exits insert mode (as it's bound in insert mode)
- The second `Ctrl-[` is unbound (in normal mode)
- OS X inserts `Û` when `Ctrl-[` is pressed
- qutebrowser thinks it's a non-alphanumeric char and forwards it

**Closed by The-Compiler** 2016-05-04 20:46 UTC
Labels: component: keyinput, OS X
