### ISSUE TITLE
Some hints are not working

### ISSUE THREAD

**Issue by antoyo** [The-Compiler/qutebrowser#1879] opened 2016-08-20 15:13 UTC
Hello.
There are some hints that are not working.
For instance, I cannot select the Search box on [this page](https://help.hushmail.com/hc/en-us) and the same happens on the "Rechercher" (Search) box on [this page](https://openclassrooms.com/).
I use the revision 679165ebabbeb3a2b63ce9d9ade1f901e7bbaeb8 from the master branch.
One solution to this issue could be to simulate the click on the center of the element.
Thanks to fix this issue.

**Comment by The-Compiler** [comment] 2016-08-20 15:42
Closing as duplicate of #1613.

**Closed by The-Compiler** 2016-08-20 15:42 UTC
