### ISSUE TITLE
hint (number-mode) does not autofollow on 2 identical hits

### ISSUE THREAD

**Issue by spiderbit** [The-Compiler/qutebrowser#1955] opened 2016-09-16 01:21 UTC
If you type in a search term that results in 2 identical results (2 times the same url) it does not autofollow.

here a example:

https://www.gnu.org/software/emacs/

scroll down to the end of the site, where see on the bottom the line:

> Home Features Releases Download ....

and you depending on your resolution should also see that line:

> The current stable release is 24.5 (released April 10, 2015; see also dates of older releases).
> To obtain it, visit the download page.

When you now start the follow command and type `dow` you should only have selected both links to the download page, you can select one of them with 0 or 1, but both link targets are the same.

So in my oppinion if it only finds identical links it should autofollow. 

That example is only to have a easy reproducable testcase. I ran into that on a youtube site, where it really hurt me (maybe a bit overdramatic phrasing) and made me wondering how much letters I need to write till its finaly unique before at some point I seen that the video was linked 2 times on the site and even typing the whole description would not start it.

**Comment by The-Compiler** [comment] 2016-09-16 06:39
Closing this as a duplicate of #71 as this is essentially the same problem.

However this is kind of tricky, as elements can have javascript click handlers installed, so even if two links seem to point to the same link, their behavior can be different. In other words, before doing something like this there'd need to be JS click handler support for hints, so only hints without such a handler could be merged that way.

**Closed by The-Compiler** 2016-09-16 06:39 UTC
