### ISSUE TITLE
"Network is disabled" error with Qt 5.5.1 after suspend/resume

### ISSUE THREAD

**Issue by tex** [The-Compiler/qutebrowser#1054] opened 2015-10-24 06:48 UTC
I get error message: try to reload after resume when I suspened with running qutebrowser.
Network connection is ok. Restarting qutebrowser helps.
Looks like some wrong network presence detection....

**Comment by The-Compiler** [comment] 2015-10-24 07:01
Probably a Qt issue I can't do much about...

What Qt version (see `:open qute:version`)? What distribution? What's the exact message you get?

**Comment by tex** [comment] 2015-10-24 08:53
qutebrowser v0.4.1
Git commit: v0.3.0-1034-gd862821 (2015-10-17 19:05:26 +0200)

CPython: 3.5.0
Qt: 5.5.0, runtime: 5.5.1
PyQt: 5.5
Style: QFusionStyle
Desktop: None
sip: 4.16.9
colorlog: no
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.0.2
yaml: 3.11
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2d 9 Jul 2015

Frozen: False
Platform: Linux-4.2.3-1-ARCH-x86_64-with-arch, 64bit
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"



--- /etc/arch-release ---

**Comment by The-Compiler** [comment] 2015-10-24 13:05
What about the last question? "I get error message: try to reload" is far too fuzzy, I'm sure there was a more specific error displayed.

**Comment by tex** [comment] 2015-10-24 17:30
Sorry. This is the error:

![snapshot2](https://cloud.githubusercontent.com/assets/27386/10711749/99c8a264-7a85-11e5-844b-19cc26872061.png)


It happens when I suspend laptop and then resume. QuteBrowser thinks that network is down even though it is up and working. I'm on wifi.

**Comment by The-Compiler** [comment] 2015-10-25 19:07
I've also seen this once, but I can't consistently reproduce it. It seems like some Qt issue introduced with Qt 5.5.1, as I've never heard about this error before...

**Comment by cptMikky** [comment] 2015-10-29 09:28
I can consistently reproduce this behaviour by following these steps:
1) Internet is accessible: open an arbitrary webpage in a tab. Page loads.
2) disconnect the network.  refresh tab: *network disabled*
3) reconnect the network. Internet is accessible. Refresh tab: *network disabled*
4) open a page in a new window or tab: page loads
5) refres the "old" tab: *network (still) disabled*

It seems that once a tab detects a network down situation, it will consider the network inaccessible indefinitely, not even trying to check whether anything changed.

----
Version info

qutebrowser v0.4.1
Git commit: v0.4.0-311-g743c3b1 (2015-10-16 06:53:07 +0200)

CPython: 3.5.0
Qt: 5.5.0, runtime: 5.5.1
PyQt: 5.5
Style: QGtkStyle
Desktop: Xfce Session
sip: 4.16.9
colorlog: no
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.0.2
yaml: 3.11
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2d 9 Jul 2015

Frozen: False
Platform: Linux-4.1.11-1-ck-x86_64-with-arch, 64bit
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"



--- /etc/arch-release ---

**Comment by ndalliard** [comment] 2015-11-19 10:17
I've the same problem. Restart of Qutebrowser solves the problem. But would be great if we can get a solution for this.

**Comment by The-Compiler** [comment] 2015-11-19 10:18
Nothing I can do. Using `gC` to clone the tab (or opening a new tab in general) works as well.

I built the 5.6 beta in the meantime after some trouble, but didn't try it yet. I'm pretty confident it's solved there though, as other projects with the same issue have confirmed that already.

**Comment by The-Compiler** [comment] 2016-01-07 09:36
Maybe qutebrowser could auto-create a new QNAM (or clone the tab and close the broken one) when this happens.

**Comment by NoSuck** [comment] 2016-01-12 23:35
As a constantly roaming qutebrowser user, this issue has affected me a great deal... until today.  The network access error no longer appears, and pages reload as expected.  I will report back later, when I know more.

**Comment by craftyguy** [comment] 2016-03-21 00:20
I upgraded to qt5.6 (Arch, it's in "testing" repo) and I can still reproduce this behavior :(

**Comment by craftyguy** [comment] 2016-03-21 00:20
I upgraded to qt5.6 (Arch, it's in "testing" repo) and I can still reproduce this behavior :(

**Comment by craftyguy** [comment] 2016-03-21 00:20
I upgraded to qt5.6 (Arch, it's in "testing" repo) and I can still reproduce this behavior :(

**Comment by Ram-Z** [comment] 2016-03-21 10:30
I experience this as well (sporadically), but it seems to be bound to 
each tab. Opening new tabs will work, but reloading the tab will not.

**Comment by tex** [comment] 2016-03-21 11:16
@Ram-Z I see the same.

**Comment by The-Compiler** [comment] 2016-03-21 11:21
Yeah, it's the `QNetworkAccessManager` class which gets into some invalid state, and each tab has its own one.

This will be gone with QtWebEngine (as it doesn't use the Qt network stack), but I might try implementing a workaround which just automatically clones the tab (`gC`) and closes the "broken" one when this happens.

**Comment by Ram-Z** [comment] 2016-03-21 14:00
Cloning tabs would be nice. Currently I just reopen the url in a new tab 
(`gO`), but unfortunately this does not copy the history.

It's a nice feature on it's own, not only as a workaround for this.

**Comment by The-Compiler** [comment] 2016-03-21 14:27
@Ram-Z You can already do `gC` or `:tab-clone`

**Comment by jgkamat** [comment] 2016-03-29 17:58
I think I'm seeing a variant of this issue when I'm on my school wireless network (maybe when I switch APs?) without any suspend/resume. Whats weird is that `tab-clone` dosent work in this situation (but `tab-clone` does fix the issue if I switch from wired -> wireless, or if I suspend/resume). If someone thinks this is different, I'll create a new issue and try to find more debuginfo.

Also, qt5.6 seems to be in the arch stable repos, but pyqt seems to still be at 5.5.1.
```
qutebrowser v0.5.1
Git commit: 

CPython: 3.5.1
Qt: 5.5.1, runtime: 5.6.0
PyQt: 5.5.1
Style: QFusionStyle
Desktop: /usr/share/xsessions/bspwm
sip: 4.18.dev1603251537
colorlog: yes
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.11
cssutils: 1.0.1 $Id$
pdf.js: 1.3.91
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2g  1 Mar 2016

Frozen: False
Platform: Linux-4.4.5-1-ARCH-x86_64-with-arch, 64bit
OS Version: 

--- /etc/arch-release ---


--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

**Comment by craftyguy** [comment] 2016-03-29 18:03
@jgkamat

Interesting, I wonder if rebuilding pyqt5.5 against qt5.6 would resolve this issue for you. I filed this bug last night to (hopefully) have pyqt rebuilt since that resolved a different issue I was experiencing due to qt5.6 hitting stable on Arch: https://bugs.archlinux.org/task/48734

**Comment by The-Compiler** [comment] 2016-03-29 18:30
> I think I'm seeing a variant of this issue occasionally when I'm on my school wireless network (maybe when I switch APs on the same network?) without any suspend/resume. Whats weird is that `tab-clone` dosent work in this situation (but `tab-clone` does fix the issue if I switch from wired -> wireless, suspend/resume, or switch wireless networks). If someone thinks this is different, I'll create a new issue and try to find more debug info.

I'm guessing it's an eduroam network? I think I've heard of other people having trouble as well where `:tab-clone` didn't help either.

Unfortunately, there really isn't much I can do (except recommending `:restart` as a workaround in your case) until Qt fixes this - at least for QtWebKit... Did I already throw an obligatory ["QtWebEngine will fix all of your problems"](http://igg.me/at/qutebrowser) at you? :wink:

> Also, qt5.6 seems to be in the arch stable repos, but pyqt seems to still be at 5.5.1.

That's expected - a 5.5 PyQt should run with a 5.6 Qt just fine, and PyQt 5.6 hasn't been released yet. This is because Qt aims to keep binary compatibility with new minor releases.

(except they accidentally[?] didn't for QtTest with Qt 5.6, which is why you'll get into trouble currently when trying to run the testsuite on Arch)

**Comment by jgkamat** [comment] 2016-03-29 18:57
I'm not on an eduroam network (but my school has a lot of nonstandard things as far as I'm aware). I'll let you know if I find anything else out, but I'm stoked for QtWebEngine support! =)

`restart` works for me, and that should be good enough for the moment, at least for me.

**Comment by lxr-shadow** [comment] 2016-05-04 16:59
Any better solution available now? I started using qutebrowser a week ago, but find this issue really annoying. I have to restart it nearly every 20 min. This substantially affects the usability of the browser.

**Comment by The-Compiler** [comment] 2016-05-04 17:24
@lxr-shadow Unfortunately not - to summarize:

- `gC` (cloning the current tab) works in some cases
- Doing `:restart` is a less painful restart in the cases `gC` doesn't
- This will be fixed when using the QtWebEngine backend which will be supported in a few weeks/months (depending on what you need to work, I guess)

But there's really not much I can do other than that :worried:

**Comment by lxr-shadow** [comment] 2016-05-04 17:36
@The-Compiler Thanks for your reply. Now I am using the `:restart` since `gC` does not work for me. I really love the feature that qutebrowser provides. :+1: Look forward to the new backend!

**Comment by Radvendii** [comment] 2016-09-07 01:33
`du` also works for me. delete the tab and then undo the deletion

**Comment by spiderbit** [comment] 2016-09-08 03:09
have also the same issue in a current installion of nixos. Sad that they have upstream a bug that long active and need soon year(s) to fix it.

**Comment by craftyguy** [comment] 2016-09-08 15:20
I'll add that while using the webengine backend, I do not experience this issue anymore.

**Comment by The-Compiler** [comment] 2016-09-08 15:33
Which makes sense, because it's a bug in Qt's networking code (where I'm not sure if there's any paid maintainer for...), and QtWebEngine uses Chromium's networking code instead.

**Comment by jgkamat** [comment] 2016-09-08 15:42
Is there a flag that we can enable to start using the webengine backend now (or are there docs somewhere on how to do so)? I searched the help quick menu but I couldnt fine anything...

**Comment by The-Compiler** [comment] 2016-09-08 15:47
`--backend webengine`, as mentioned in the [manpage](https://github.com/The-Compiler/qutebrowser/blob/master/doc/qutebrowser.1.asciidoc) (which is not part of the `:help` system, as you already started qutebrowser at that point anyways :wink:)

**Comment by The-Compiler** [comment] 2017-01-24 22:09
Since QtWebEngine is the future™, I don't want to add an ugly workaround for this, so I'm closing it.

**Closed by The-Compiler** 2017-01-24 22:09 UTC
Labels: priority: 1 - middle, qt

**Comment by ibr123** [comment] 2018-09-02 14:47
I'm using **Qt 5.10 on Visual Studio 2017**, this error is more frequent on **Release** build rather than **Debug** build, do you have any idea on how to solve this issue? i have been searching all around but no luck

**Comment by The-Compiler** [comment] 2018-09-02 16:11
@ibr123 It's a bug in Qt, this probably isn't really the right place for general Qt questions. I'm surprised to hear that you're still having trouble though, looking at e.g. [this Qt bug](https://bugreports.qt.io/browse/QTBUG-55180) it seems to [have been fixed](https://codereview.qt-project.org/#/c/212187/) with Qt 5.9.6 (and 5.10).
