### ISSUE TITLE
Data URLs for large files in history cause slowdown

### ISSUE THREAD

**Issue by tomxtobin** [The-Compiler/qutebrowser#1721] opened 2016-08-01 17:24 UTC
If you open a `data:` URL representing a large file, it greatly slows down searching your quickmarks/history/etc. Manually removing the URL from history resolves the issue.

I'm running off `master`.

**Comment by The-Compiler** [comment] 2016-08-01 19:03
Closing as duplicate of #1099.

**Closed by The-Compiler** 2016-08-01 19:03 UTC
