### ISSUE TITLE
 sort history by how many times visited

### ISSUE THREAD

**Issue by tex** [The-Compiler/qutebrowser#945] opened 2015-09-13 08:45 UTC
when I hit open, list of previously visited pages is shown as history. it would be nice to sort this list according to number of times I have visited them.

**Comment by meles5** [comment] 2015-09-13 08:49
But then it wouldn't be a real history - more a "popular sites" list - it would be better to have an option to switch between those things

**Comment by The-Compiler** [comment] 2015-09-13 20:09
This is a duplicate of #601 - but it'll definitely be configurable, yeah.

**Closed by The-Compiler** 2015-09-13 20:09 UTC
