### ISSUE TITLE
Add option to get file dialog for downloads

### ISSUE THREAD

**Issue by mgoral** [The-Compiler/qutebrowser#1609] opened 2016-06-30 17:10 UTC
Currently telling qutebrowser where it should download files can be quite cumbersome because we have to exactly know the full download path and it gets harder the more directories there are. How about easing it up?

The easiest thing that comes to my mind is simply showing `QFileDialog::getExistingDirectory()`. But if you feel that displaying popup windows is against qutebrowser's spirit, maybe autocompleting path when user presses tab (like Bash and Vim do) is the way to go. What do you guys think?

**Comment by The-Compiler** [comment] 2016-06-30 17:31
I agree it'd be best to have a completion - either just like the current completion (see #32 for that), or at least a simple tab-completion without much UI - I think @NoctuaNivalis wanted to work on the latter, but I'm not sure what the current state is.

I thought about adding an option to just display a file dialog as well, but then kind of forgot about it. I'll reporpuse this issue for that idea, which should be fairly easy to implement.

**Comment by martingabelmann** [comment] 2016-07-01 16:29
+1 for the simple tab-completion :+1:

**Comment by tuxlovesyou** [comment] 2016-07-01 20:58
I think we should make it something in the middle; use the UI for opening urls with tab-completion :)

**Comment by The-Compiler** [comment] 2016-07-01 21:00
> I think we should make it something in the middle; use the UI for opening urls with tab-completion :)

That's how the current completion already works, no?

**Comment by tuxlovesyou** [comment] 2016-07-01 21:01
>  That's how the current completion already works, no?

But with the list UI, too (and tab-completion)

**Comment by NoctuaNivalis** [comment] 2016-07-02 08:52
I got started on this (the simple completion), but got stuck with the current completion model. I'd have to use quite some hacks to get this into it. I was planning to continue this later when the completion model was reviewed.

**Comment by The-Compiler** [comment] 2016-07-03 15:35
@NoctuaNivalis I don't really follow - if you add tab completion for the filename prompt (i.e. in `KeyMode.prompt`, not `KeyMode.command`), that should be completely unrelated to the command completion, no?

**Comment by NoctuaNivalis** [comment] 2016-07-03 17:42
Oh, I was planning "simple completion" with the usual completion, not just tab completion. That might be easier ;-)

**Comment by The-Compiler** [comment] 2016-07-04 05:59
@NoctuaNivalis Want to try implementing that? I think until the completion refactoring is done it'll still take some while, and a lot of people (including me and you I think?) would be really glad if there at least was *some* form of completion, even without much UI.

**Comment by Kingdread** [comment] 2016-07-08 09:16
The "file dialog" part is probably a duplicate of #1365.

**Comment by The-Compiler** [comment] 2016-07-08 09:17
Oh, indeed - closing this as duplicate of #32 and #1365 then.

**Closed by The-Compiler** 2016-07-08 09:17 UTC
Labels: component: downloads, easy, priority: 2 - low
