### ISSUE TITLE
Imgur freezing

### ISSUE THREAD

**Issue by nevvi** [The-Compiler/qutebrowser#1762] opened 2016-08-04 01:24 UTC
Every time I visit Imgurs site the browser freezes for at least 30 secs. I can open a tab in the background without issues as long as I don't open that tab. No other site I've encountered has caused the same problem.

Running Xubuntu 16.04 with following specs:
```
Version info

qutebrowser v0.8.1
Git commit: 

CPython: 3.5.2
Qt: 5.5.1
PyQt: 5.5.1

sip: 4.17
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.11
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: no
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2g-fips  1 Mar 2016

Style: QGtkStyle
Platform: Linux-4.4.0-31-generic-x86_64-with-Ubuntu-16.04-xenial, 64bit
Desktop: xubuntu
Frozen: False
Imported from /usr/local/lib/python3.5/dist-packages/qutebrowser-0.8.1-py3.5.egg/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
UBUNTU_CODENAME=xenial

--- /etc/lsb-release ---
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
```

**Comment by The-Compiler** [comment] 2016-08-04 05:16
If you start qutebrowser with `--temp-basedir --debug` in a terminal, does this also happen? When it happens, do you see any interesting output in the terminal?

**Comment by The-Compiler** [comment] 2016-08-09 04:30
@nevvi Any update?

**Comment by nevvi** [comment] 2016-08-09 15:01
So sorry, forgot to try this and I'll be away from my computer for some time. Can I get back to you around the 24th?

**Comment by The-Compiler** [comment] 2016-08-09 15:03
Sure, thanks for the update!

**Comment by erikryb** [comment] 2016-08-20 12:45
I can confirm this behaviour. Here is the output of running
`qutebrowser --temp-basedir --debug "https://imgur.com/gallery/tOEFZ#NuGAoW7" `

[http://sprunge.us/YVJV](http://sprunge.us/YVJV)

**Comment by erikryb** [comment] 2016-08-20 12:57
The problem seems to go away when disabling javascript:
`qutebrowser --temp-basedir --debug :"set content allow-javascript false" "https://imgur.com/gallery/tOEFZ#NuGAoW7"`

Log: [http://sprunge.us/jYIY](http://sprunge.us/jYIY)

**Comment by erikryb** [comment] 2016-08-20 13:28
The same thing also happens (more or less) in uzbl, luakit, dwb and surf.

**Comment by The-Compiler** [comment] 2016-08-20 14:59
Some ideas:

- If you have `gstreamer-vaapi` installed, try uninstalling it
- If you have no `mozplugger` installed, but a leftover ``~/.mozilla/plugins/mozplugger*.so`, try deleting it

**Comment by nevvi** [comment] 2016-09-18 22:45
Sorry, completely forgot about this issue since Imgur's been working. Unfortunately I don't recall anything specific that could have caused it though.

**Comment by The-Compiler** [comment] 2016-09-19 04:20
@nevvi No problem, glad to hear it's working again!

@erikryb what about you?

**Comment by erikryb** [comment] 2016-09-26 12:33
It seems to be working for me now.

**Comment by The-Compiler** [comment] 2016-09-26 13:01
Closing this then!

**Closed by The-Compiler** 2016-09-26 13:01 UTC
