### ISSUE TITLE
Default web browser

### ISSUE THREAD

**Issue by xtuc** [The-Compiler/qutebrowser#1666] opened 2016-07-19 20:32 UTC
Please remember to mention your version info (qutebrowser, Qt, PyQt,
OS/distribution) from the `qute:version` page or `qutebrowser --version`

---

Hi,

I'm not able to select Qutebrowser as my default web browser on Mac osx. I guess on Mac you can declare yourself as an browser, like IEs which are running in Virtual Machines.

Thanks,
Sven

```
qutebrowser v0.7.0
Platform: Darwin-14.5.0-x86_64-i386-64bit, 64bit
OS Version: 10.10.5, x86_64
```

<img width="457" alt="screen shot 2016-07-19 at 22 24 37" src="https://cloud.githubusercontent.com/assets/1493671/16965348/efdebf5a-4dff-11e6-9c44-43919fa0ff3c.png">

**Comment by The-Compiler** [comment] 2016-07-19 20:36
Closing as a duplicate of #22.

**Closed by The-Compiler** 2016-07-19 20:36 UTC
