### ISSUE TITLE
Javascript/popup issues on Github.com

### ISSUE THREAD

**Issue by shioyama** [The-Compiler/qutebrowser#1255] opened 2016-01-20 04:41 UTC
First thanks for a great browser! I really love qutebrowser and have switched to it entirely after struggling with pentadactyl/firefox and other simple browsers.

However as of today I'm getting a very strange issue that I can't quite explain on github.com. I first noticed that clicking on "Labels"/"Milestones"/"Assignee" would not bring up the expected javascript box, then also noticed that adding inline comments to code did not work (no "+" shown). Also switching tabs in the PR pages is sluggish because it's actually reloading the page rather than doing the work on the client side.

I figured something was going wrong with the javascript but the only error I see in the web inspector console is "ReferenceError: Can't find variable: Promise ", which may not be related.

I'm not 100% sure but I'm pretty sure that I did not have this issue earlier. I'm running the latest version of qutebrowser:

```
~ qutebrowser --version
qutebrowser v0.5.1
Git commit: v0.5.0-159-geb276df (2016-01-19 07:03:43 +0100)

CPython: 3.5.1
Qt: 5.5.1, runtime: 5.5.1
PyQt: 5.5.1
```

Any ideas or suggestions as to what I might do to debug this issue would be much appreciated! I've checked in other browsers and the same pages work fine there, and javascript is not disabled. I've also disabled the blocking list but that doesn't change anything, and tried changing my user agent but that doesn't help either...

**Comment by The-Compiler** [comment] 2016-01-20 05:19
Unfortunately I'm seeing the very same issues with any QtWebKit based browser :worried:

I contacted GitHub support, and I'd like to ask you to do the same. The same thing already happened before, and after enough people contacted them it was fixed :wink:

**Comment by vyp** [comment] 2016-01-20 05:48
Getting the same errors, therefore probably a github issue.

**Comment by vyp** [comment] 2016-01-20 05:48
Getting the same errors, therefore probably a github issue.

**Comment by shioyama** [comment] 2016-01-20 06:23
Ah okay good to hear it's not just me! I'll contact them too.

**Comment by shioyama** [comment] 2016-01-20 06:23
Ah okay good to hear it's not just me! I'll contact them too.

**Comment by shioyama** [comment] 2016-01-20 08:32
Got an email from github support saying they were forwarding this to their devs, hoping we'll see this fixed soon!

**Comment by vyp** [comment] 2016-01-22 07:09
@shioyama are you still getting these errors? (I am.) What about everyone else, can any other qutebrowser users here confirm that they are getting these issues?

**Comment by The-Compiler** [comment] 2016-01-22 07:10
I'm still seeing those issues too. Someone in `#qutebrowser` mentioned they're gone, but they're still there for everybody else.

**Comment by vyp** [comment] 2016-01-22 07:23
@The-Compiler yup that's why I asked, just to confirm that it's not something peculiar with my system. Thanks.

**Comment by lamarpavel** [comment] 2016-01-22 09:51
I still have them as well. @vyp, please contact the support as well, if you haven't already.

**Comment by Zaplanincan** [comment] 2016-01-22 11:41
I have problems two days ago, today everything is OK.
Instaled from Arch AUR:
qutebrowser v0.5.1
Git commit: 
CPython: 3.5.1
Qt: 5.5.1, runtime: 5.5.1
PyQt: 5.5.1

**Comment by vyp** [comment] 2016-01-22 11:43
@lamarpavel I have of course, two days ago. Got the same response as @shioyama.

**Comment by The-Compiler** [comment] 2016-01-22 11:56
It actually works for me after I changed my user-agent back to the default. With a Chromium UA, it's still broken.

**Comment by NoctuaNivalis** [comment] 2016-01-22 12:16
Oh this happens to me on other sites, too. If the website uses browser-specific javascript/css, the site breaks when your user-agent lies.

**Comment by shioyama** [comment] 2016-01-22 12:44
I can confirm that it works for me if I change my user-agent to `""`. But I'm 100% sure that a couple days ago it was breaking no matter what user-agent I used, so I guess github must have made the changes user-agent-specific. So no more spoofing another user-agent for me I guess... anyway just glad it works again!

**Comment by The-Compiler** [comment] 2016-01-22 12:52
> But I'm 100% sure that a couple days ago it was breaking no matter what user-agent I used

I can confirm that as well.

Closing this for now, as there isn't much more we can do - and as you said, I'm happy it works with the default user agent again at least!

**Closed by The-Compiler** 2016-01-22 12:52 UTC

**Comment by shioyama** [comment] 2016-01-22 13:23
Thanks @The-Compiler ! The web should ideally be more user-agent agnostic, but I guess that's not where things are going these days...
