### ISSUE TITLE
Suboptimal column widths for completion view

### ISSUE THREAD

**Issue by lahwaacz** [The-Compiler/qutebrowser#1582] opened 2016-06-13 19:18 UTC
See the screenshot: http://postimg.org/image/mv1s7tiaf/

There is plenty of space to show all necessary information, but since the window does not have full width, part of the date is cut off. Ideally the column widths would scale according to the content to be displayed.

**Comment by The-Compiler** [comment] 2016-06-14 06:07
Closing as duplicate of #693.

**Closed by The-Compiler** 2016-06-14 06:07 UTC
