### ISSUE TITLE
Better way to restore pages

### ISSUE THREAD

**Issue by antoyo** [The-Compiler/qutebrowser#966] opened 2015-09-26 14:44 UTC
Currently, qutebrowser will only offer to restore the opened pages when it is able to recover from a crash.
It does not work when the browser segfaults (it happens to me from times to times, but I cannot reproduce) or when there is a power outage and the computer unexpectedly shutdown for instance.
I believe qutebrowser should be able to restore the opened pages in these cases as well.
For that, it should save the opened pages from times to times in a file and delete this file on a correct shutdown of the application.
In case the application did not shutdown correctly, it would see this file and ask to the user if (s)he wants to restore the pages.

**Comment by The-Compiler** [comment] 2015-09-26 15:15
Duplicate of #11

**Closed by The-Compiler** 2015-09-26 15:15 UTC
