### ISSUE TITLE
Fuzzy history completion

### ISSUE THREAD

**Issue by kirelagin** [The-Compiler/qutebrowser#785] opened 2015-06-24 22:12 UTC
When I type `o git qute iss` I expect completion to suggest `https://github.com/The-Compiler/qutebrowser/issues/`.

**Comment by kirelagin** [comment] 2015-06-24 22:12
This is probably true not only for history.

**Comment by The-Compiler** [comment] 2015-06-25 08:19
Closing this as a duplicate of #133.

**Closed by The-Compiler** 2015-06-25 08:19 UTC
