### ISSUE TITLE
Add issue/pull request templates

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1379] opened 2016-03-30 06:06 UTC
See [GitHub blogpost](https://github.com/blog/2111-issue-and-pull-request-templates)

**Comment by ff2000** [comment] 2016-04-01 07:09
If you create such templates please keep them small and simple.
Look at Valloric/YouCompleteMe -- I think that is way too much.
Looks like a contract. Especially merged PRs clutter the git log.
(And TBH I did not create new issues for several projects because
I just went crazy because it made me feel stupid ;))
Those Ticklists IMHO are counterproductive as they suggest some
WIP is happening.
IMO neovim does a great job in this regard.

IMHO a sane approach would be to help formatting the issue/PR by
adding headings and lists for system information, steps to
reproduce, etc. Also linking to a verbose CONTRIBUTING file is
IMO OK.
Ask yourself if you ever would get better issue reports or PRs
with such gigantic "contracts" - templates. I think you can
trust your users to be no idiots ;)

On Tue, 29 Mar 2016 23:06:14 -0700, Florian Bruhin <notifications@github.com> wrote:
> See [GitHub blogpost](https://github.com/blog/2111-issue-and-pull-request-templates)
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/The-Compiler/qutebrowser/issues/1379
> 
--

**Comment by The-Compiler** [comment] 2016-04-01 07:50
I agree something like the neovim one does make more sense than the YCM one. It's a shame Markdown doesn't seem to have something like comments.

> Especially merged PRs clutter the git log.

I don't understand - the text you enter in GitHub for a PR is independent from the commit message.

**Comment by NoctuaNivalis** [comment] 2016-04-01 08:30
How about:

```markdown
Version info (surf to `qute://version` in qutebrowser if possible):
```
```

### Actual behaviour

### Expected behaviour

### Steps to reproduce
```

That page should provide all info.

**Comment by rcorre** [comment] 2016-07-04 23:35
Just my 2cents: I feel like this kind of thing typically just gets in the way. We have a template just like this at work and the majority of the time I just delete the whole thing to input my bug. Usually describing the actual behavior automatically includes repro steps, and the expected behavior is implied. If I file a bug that says 'doing this crashes qutebrowser', do I really need another section to say 'Expected result: qutebrowser doesn't crash'?

There are cases where this is useful, but in the majority it is a hindrance (though qutebrowser's `open-editor` does make these kind of things less painful).

**Comment by The-Compiler** [comment] 2016-07-05 15:47
I do agree, which is why I want to make this rather simple, compared to other things I've seen. Still thinking about it now that a PR (#1623) has been opened.

I think at least a note to add the version info would be nice though, as that's something people often forget (and I even do myself when reporting bugs for other software).

**Comment by rcorre** [comment] 2016-07-06 00:29
Fair enough, I think a reminder to include version info is worthwhile.

**Comment by lahwaacz** [comment] 2016-07-14 19:02
Another problem is that github issues cover everything - bug reports, feature requests, personal support, general questions - you name it. The current [ISSUE_TEMPLATE.md](https://github.com/The-Compiler/qutebrowser/blob/9bd2c6048818aefac27d95eb175d1fb6318f318c/.github/ISSUE_TEMPLATE.md) covers only bug reports, so it should at least start with "If reporting a bug, ..." or something like that to not confuse people dealing with the other points. Also, doesn't it somewhat compete with `:report` or shouldn't it at least be mentioned?

Also, the current [ISSUE_TEMPLATE.md](https://github.com/The-Compiler/qutebrowser/blob/9bd2c6048818aefac27d95eb175d1fb6318f318c/.github/ISSUE_TEMPLATE.md) is not much of a template - it's just something like bug reporting guidelines squeezed into a single sentence, not something the users can base their report on. The users should acknowledge it, delete it and write their report. The included horizontal line has been proved confusing at least once: https://github.com/The-Compiler/qutebrowser/issues/1628

When you open the "New issue" form, there is a note at the top with a link to review "guidelines for contributing" (aka CONTRIBUTING.md). IMHO it would have been much better if this note was shown in the "pull request" form. Then there could be a different document with guidelines for creating issues, which would cover the points mentioned above. Important notes (if not the whole document) could even be sticky inside the note itself. Github obviously does not support all that, but IMO it should.

**Comment by The-Compiler** [comment] 2016-08-05 06:15
@lahwaacz Thanks for the feedback! After watching the results of this for a while, I (hopefully) improved the "template" a bit in 9a50daafeeaae737612e2e2f6ce110269c463a09.

It's now a HTML comment and thus ignored by GitHub - so the only thing which could go wrong is that users add their version information (or issue) *inside* the comment, which I hope won't happen :laughing: 

It also mentions that the version information is needed for bugs only. I decided to not mention `:report` - it can be useful in cases I can't reproduce myself, but in many non-crash bugs it's not needed.

I agree with your comment about GitHub (it *does* show the same box about the contributing docs on PR s though), but there's only so much I can do :wink:

**Closed** 2016-08-05 06:16 UTC
Labels: easy, not code, priority: 1 - middle
