### ISSUE TITLE
Gibrish characters in dropdown text menu

### ISSUE THREAD

**Issue by sim590** [The-Compiler/qutebrowser#1475] opened 2016-05-06 19:12 UTC
When going to this [page](http://www.crucial.com/usa/en/memory-info?cm_re=top-nav-_-flyout-memory-_-us-memory), I experience <a href="https://vimeo.com/165621464">this</a>.

Sorry for linking to a video, but it was simpler since I couldn't take screenshot when focus was on the drop down menu. Pay attention to the text in the dropdown menu. This is supposed to be english, but it's written in some language I don't understand.

**Comment by The-Compiler** [comment] 2016-05-06 21:55
This has been reported (in the IRC channel if I remember correctly) before - unfortunately this is another issue where it's the current backend's fault (QtWebKit), and which will get fixed by [supporting QtWebEngine](http://igg.me/at/qutebrowser) soon.

However I can't reproduce it, but no idea why...

**Closed by The-Compiler** 2016-05-06 21:55 UTC
